-- nios_system.vhd

-- Generated using ACDS version 13.1 162 at 2026.03.20.08:24:33

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity nios_system is
	port (
		clk_clk                                 : in    std_logic                     := '0';             --                              clk.clk
		reset_reset_n                           : in    std_logic                     := '0';             --                            reset.reset_n
		switches_export                         : in    std_logic_vector(7 downto 0)  := (others => '0'); --                         switches.export
		leds_export                             : out   std_logic_vector(7 downto 0);                     --                             leds.export
		sdram_wire_addr                         : out   std_logic_vector(12 downto 0);                    --                       sdram_wire.addr
		sdram_wire_ba                           : out   std_logic_vector(1 downto 0);                     --                                 .ba
		sdram_wire_cas_n                        : out   std_logic;                                        --                                 .cas_n
		sdram_wire_cke                          : out   std_logic;                                        --                                 .cke
		sdram_wire_cs_n                         : out   std_logic;                                        --                                 .cs_n
		sdram_wire_dq                           : inout std_logic_vector(15 downto 0) := (others => '0'); --                                 .dq
		sdram_wire_dqm                          : out   std_logic_vector(1 downto 0);                     --                                 .dqm
		sdram_wire_ras_n                        : out   std_logic;                                        --                                 .ras_n
		sdram_wire_we_n                         : out   std_logic;                                        --                                 .we_n
		cntrl_left_export                       : out   std_logic_vector(15 downto 0);                    --                       cntrl_left.export
		cntrl_right_export                      : out   std_logic_vector(15 downto 0);                    --                      cntrl_right.export
		data_0r_external_connection_export      : in    std_logic_vector(7 downto 0)  := (others => '0'); --      data_0r_external_connection.export
		data_ready_r_external_connection_export : in    std_logic                     := '0';             -- data_ready_r_external_connection.export
		vect_cap_external_connection_export     : in    std_logic_vector(6 downto 0)  := (others => '0'); --     vect_cap_external_connection.export
		niveau_external_connection_export       : out   std_logic_vector(7 downto 0);                     --       niveau_external_connection.export
		start_sl_external_connection_export     : out   std_logic;                                        --     start_sl_external_connection.export
		pos_ligne_external_connection_export    : in    std_logic_vector(3 downto 0)  := (others => '0'); --    pos_ligne_external_connection.export
		state_crtl_external_connection_export   : in    std_logic_vector(1 downto 0)  := (others => '0'); --   state_crtl_external_connection.export
		sdram_clk_clk                           : out   std_logic                                         --                        sdram_clk.clk
	);
end entity nios_system;

architecture rtl of nios_system is
	component nios_system_CPU is
		port (
			clk                                   : in  std_logic                     := 'X';             -- clk
			reset_n                               : in  std_logic                     := 'X';             -- reset_n
			reset_req                             : in  std_logic                     := 'X';             -- reset_req
			d_address                             : out std_logic_vector(26 downto 0);                    -- address
			d_byteenable                          : out std_logic_vector(3 downto 0);                     -- byteenable
			d_read                                : out std_logic;                                        -- read
			d_readdata                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			d_waitrequest                         : in  std_logic                     := 'X';             -- waitrequest
			d_write                               : out std_logic;                                        -- write
			d_writedata                           : out std_logic_vector(31 downto 0);                    -- writedata
			jtag_debug_module_debugaccess_to_roms : out std_logic;                                        -- debugaccess
			i_address                             : out std_logic_vector(26 downto 0);                    -- address
			i_read                                : out std_logic;                                        -- read
			i_readdata                            : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			i_waitrequest                         : in  std_logic                     := 'X';             -- waitrequest
			d_irq                                 : in  std_logic_vector(31 downto 0) := (others => 'X'); -- irq
			jtag_debug_module_resetrequest        : out std_logic;                                        -- reset
			jtag_debug_module_address             : in  std_logic_vector(8 downto 0)  := (others => 'X'); -- address
			jtag_debug_module_byteenable          : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			jtag_debug_module_debugaccess         : in  std_logic                     := 'X';             -- debugaccess
			jtag_debug_module_read                : in  std_logic                     := 'X';             -- read
			jtag_debug_module_readdata            : out std_logic_vector(31 downto 0);                    -- readdata
			jtag_debug_module_waitrequest         : out std_logic;                                        -- waitrequest
			jtag_debug_module_write               : in  std_logic                     := 'X';             -- write
			jtag_debug_module_writedata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			no_ci_readra                          : out std_logic                                         -- readra
		);
	end component nios_system_CPU;

	component nios_system_MEMOIRE_INTERNE is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			address    : in  std_logic_vector(9 downto 0)  := (others => 'X'); -- address
			clken      : in  std_logic                     := 'X';             -- clken
			chipselect : in  std_logic                     := 'X';             -- chipselect
			write      : in  std_logic                     := 'X';             -- write
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			byteenable : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			reset      : in  std_logic                     := 'X';             -- reset
			reset_req  : in  std_logic                     := 'X'              -- reset_req
		);
	end component nios_system_MEMOIRE_INTERNE;

	component nios_system_INPUT is
		port (
			clk      : in  std_logic                     := 'X';             -- clk
			reset_n  : in  std_logic                     := 'X';             -- reset_n
			address  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata : out std_logic_vector(31 downto 0);                    -- readdata
			in_port  : in  std_logic_vector(7 downto 0)  := (others => 'X')  -- export
		);
	end component nios_system_INPUT;

	component nios_system_OUTPUT is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			reset_n    : in  std_logic                     := 'X';             -- reset_n
			address    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			write_n    : in  std_logic                     := 'X';             -- write_n
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			chipselect : in  std_logic                     := 'X';             -- chipselect
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			out_port   : out std_logic_vector(7 downto 0)                      -- export
		);
	end component nios_system_OUTPUT;

	component nios_system_JTAG_UART is
		port (
			clk            : in  std_logic                     := 'X';             -- clk
			rst_n          : in  std_logic                     := 'X';             -- reset_n
			av_chipselect  : in  std_logic                     := 'X';             -- chipselect
			av_address     : in  std_logic                     := 'X';             -- address
			av_read_n      : in  std_logic                     := 'X';             -- read_n
			av_readdata    : out std_logic_vector(31 downto 0);                    -- readdata
			av_write_n     : in  std_logic                     := 'X';             -- write_n
			av_writedata   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			av_waitrequest : out std_logic;                                        -- waitrequest
			av_irq         : out std_logic                                         -- irq
		);
	end component nios_system_JTAG_UART;

	component nios_system_SDRAM is
		port (
			clk            : in    std_logic                     := 'X';             -- clk
			reset_n        : in    std_logic                     := 'X';             -- reset_n
			az_addr        : in    std_logic_vector(23 downto 0) := (others => 'X'); -- address
			az_be_n        : in    std_logic_vector(1 downto 0)  := (others => 'X'); -- byteenable_n
			az_cs          : in    std_logic                     := 'X';             -- chipselect
			az_data        : in    std_logic_vector(15 downto 0) := (others => 'X'); -- writedata
			az_rd_n        : in    std_logic                     := 'X';             -- read_n
			az_wr_n        : in    std_logic                     := 'X';             -- write_n
			za_data        : out   std_logic_vector(15 downto 0);                    -- readdata
			za_valid       : out   std_logic;                                        -- readdatavalid
			za_waitrequest : out   std_logic;                                        -- waitrequest
			zs_addr        : out   std_logic_vector(12 downto 0);                    -- export
			zs_ba          : out   std_logic_vector(1 downto 0);                     -- export
			zs_cas_n       : out   std_logic;                                        -- export
			zs_cke         : out   std_logic;                                        -- export
			zs_cs_n        : out   std_logic;                                        -- export
			zs_dq          : inout std_logic_vector(15 downto 0) := (others => 'X'); -- export
			zs_dqm         : out   std_logic_vector(1 downto 0);                     -- export
			zs_ras_n       : out   std_logic;                                        -- export
			zs_we_n        : out   std_logic                                         -- export
		);
	end component nios_system_SDRAM;

	component nios_system_CNTRL_LEFT is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			reset_n    : in  std_logic                     := 'X';             -- reset_n
			address    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			write_n    : in  std_logic                     := 'X';             -- write_n
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			chipselect : in  std_logic                     := 'X';             -- chipselect
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			out_port   : out std_logic_vector(15 downto 0)                     -- export
		);
	end component nios_system_CNTRL_LEFT;

	component nios_system_DATA_READY_R is
		port (
			clk      : in  std_logic                     := 'X';             -- clk
			reset_n  : in  std_logic                     := 'X';             -- reset_n
			address  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata : out std_logic_vector(31 downto 0);                    -- readdata
			in_port  : in  std_logic                     := 'X'              -- export
		);
	end component nios_system_DATA_READY_R;

	component nios_system_VECT_CAP is
		port (
			clk      : in  std_logic                     := 'X';             -- clk
			reset_n  : in  std_logic                     := 'X';             -- reset_n
			address  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata : out std_logic_vector(31 downto 0);                    -- readdata
			in_port  : in  std_logic_vector(6 downto 0)  := (others => 'X')  -- export
		);
	end component nios_system_VECT_CAP;

	component nios_system_START_SL is
		port (
			clk        : in  std_logic                     := 'X';             -- clk
			reset_n    : in  std_logic                     := 'X';             -- reset_n
			address    : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			write_n    : in  std_logic                     := 'X';             -- write_n
			writedata  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			chipselect : in  std_logic                     := 'X';             -- chipselect
			readdata   : out std_logic_vector(31 downto 0);                    -- readdata
			out_port   : out std_logic                                         -- export
		);
	end component nios_system_START_SL;

	component nios_system_POS_LIGNE is
		port (
			clk      : in  std_logic                     := 'X';             -- clk
			reset_n  : in  std_logic                     := 'X';             -- reset_n
			address  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata : out std_logic_vector(31 downto 0);                    -- readdata
			in_port  : in  std_logic_vector(3 downto 0)  := (others => 'X')  -- export
		);
	end component nios_system_POS_LIGNE;

	component nios_system_STATE_CRTL is
		port (
			clk      : in  std_logic                     := 'X';             -- clk
			reset_n  : in  std_logic                     := 'X';             -- reset_n
			address  : in  std_logic_vector(1 downto 0)  := (others => 'X'); -- address
			readdata : out std_logic_vector(31 downto 0);                    -- readdata
			in_port  : in  std_logic_vector(1 downto 0)  := (others => 'X')  -- export
		);
	end component nios_system_STATE_CRTL;

	component nios_system_clocks is
		port (
			CLOCK_50    : in  std_logic := 'X'; -- clk
			reset       : in  std_logic := 'X'; -- reset
			sys_clk     : out std_logic;        -- clk
			sys_reset_n : out std_logic;        -- reset_n
			SDRAM_CLK   : out std_logic         -- clk
		);
	end component nios_system_clocks;

	component nios_system_mm_interconnect_0 is
		port (
			clk_0_clk_clk                            : in  std_logic                     := 'X';             -- clk
			clocks_sys_clk_clk                       : in  std_logic                     := 'X';             -- clk
			CPU_reset_n_reset_bridge_in_reset_reset  : in  std_logic                     := 'X';             -- reset
			OUTPUT_reset_reset_bridge_in_reset_reset : in  std_logic                     := 'X';             -- reset
			CPU_data_master_address                  : in  std_logic_vector(26 downto 0) := (others => 'X'); -- address
			CPU_data_master_waitrequest              : out std_logic;                                        -- waitrequest
			CPU_data_master_byteenable               : in  std_logic_vector(3 downto 0)  := (others => 'X'); -- byteenable
			CPU_data_master_read                     : in  std_logic                     := 'X';             -- read
			CPU_data_master_readdata                 : out std_logic_vector(31 downto 0);                    -- readdata
			CPU_data_master_write                    : in  std_logic                     := 'X';             -- write
			CPU_data_master_writedata                : in  std_logic_vector(31 downto 0) := (others => 'X'); -- writedata
			CPU_data_master_debugaccess              : in  std_logic                     := 'X';             -- debugaccess
			CPU_instruction_master_address           : in  std_logic_vector(26 downto 0) := (others => 'X'); -- address
			CPU_instruction_master_waitrequest       : out std_logic;                                        -- waitrequest
			CPU_instruction_master_read              : in  std_logic                     := 'X';             -- read
			CPU_instruction_master_readdata          : out std_logic_vector(31 downto 0);                    -- readdata
			CNTRL_LEFT_s1_address                    : out std_logic_vector(1 downto 0);                     -- address
			CNTRL_LEFT_s1_write                      : out std_logic;                                        -- write
			CNTRL_LEFT_s1_readdata                   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			CNTRL_LEFT_s1_writedata                  : out std_logic_vector(31 downto 0);                    -- writedata
			CNTRL_LEFT_s1_chipselect                 : out std_logic;                                        -- chipselect
			CNTRL_RIGHT_s1_address                   : out std_logic_vector(1 downto 0);                     -- address
			CNTRL_RIGHT_s1_write                     : out std_logic;                                        -- write
			CNTRL_RIGHT_s1_readdata                  : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			CNTRL_RIGHT_s1_writedata                 : out std_logic_vector(31 downto 0);                    -- writedata
			CNTRL_RIGHT_s1_chipselect                : out std_logic;                                        -- chipselect
			CPU_jtag_debug_module_address            : out std_logic_vector(8 downto 0);                     -- address
			CPU_jtag_debug_module_write              : out std_logic;                                        -- write
			CPU_jtag_debug_module_read               : out std_logic;                                        -- read
			CPU_jtag_debug_module_readdata           : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			CPU_jtag_debug_module_writedata          : out std_logic_vector(31 downto 0);                    -- writedata
			CPU_jtag_debug_module_byteenable         : out std_logic_vector(3 downto 0);                     -- byteenable
			CPU_jtag_debug_module_waitrequest        : in  std_logic                     := 'X';             -- waitrequest
			CPU_jtag_debug_module_debugaccess        : out std_logic;                                        -- debugaccess
			DATA_0R_s1_address                       : out std_logic_vector(1 downto 0);                     -- address
			DATA_0R_s1_readdata                      : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			DATA_READY_R_s1_address                  : out std_logic_vector(1 downto 0);                     -- address
			DATA_READY_R_s1_readdata                 : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			INPUT_s1_address                         : out std_logic_vector(1 downto 0);                     -- address
			INPUT_s1_readdata                        : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			JTAG_UART_avalon_jtag_slave_address      : out std_logic_vector(0 downto 0);                     -- address
			JTAG_UART_avalon_jtag_slave_write        : out std_logic;                                        -- write
			JTAG_UART_avalon_jtag_slave_read         : out std_logic;                                        -- read
			JTAG_UART_avalon_jtag_slave_readdata     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			JTAG_UART_avalon_jtag_slave_writedata    : out std_logic_vector(31 downto 0);                    -- writedata
			JTAG_UART_avalon_jtag_slave_waitrequest  : in  std_logic                     := 'X';             -- waitrequest
			JTAG_UART_avalon_jtag_slave_chipselect   : out std_logic;                                        -- chipselect
			MEMOIRE_INTERNE_s1_address               : out std_logic_vector(9 downto 0);                     -- address
			MEMOIRE_INTERNE_s1_write                 : out std_logic;                                        -- write
			MEMOIRE_INTERNE_s1_readdata              : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			MEMOIRE_INTERNE_s1_writedata             : out std_logic_vector(31 downto 0);                    -- writedata
			MEMOIRE_INTERNE_s1_byteenable            : out std_logic_vector(3 downto 0);                     -- byteenable
			MEMOIRE_INTERNE_s1_chipselect            : out std_logic;                                        -- chipselect
			MEMOIRE_INTERNE_s1_clken                 : out std_logic;                                        -- clken
			NIVEAU_s1_address                        : out std_logic_vector(1 downto 0);                     -- address
			NIVEAU_s1_write                          : out std_logic;                                        -- write
			NIVEAU_s1_readdata                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			NIVEAU_s1_writedata                      : out std_logic_vector(31 downto 0);                    -- writedata
			NIVEAU_s1_chipselect                     : out std_logic;                                        -- chipselect
			OUTPUT_s1_address                        : out std_logic_vector(1 downto 0);                     -- address
			OUTPUT_s1_write                          : out std_logic;                                        -- write
			OUTPUT_s1_readdata                       : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			OUTPUT_s1_writedata                      : out std_logic_vector(31 downto 0);                    -- writedata
			OUTPUT_s1_chipselect                     : out std_logic;                                        -- chipselect
			POS_LIGNE_s1_address                     : out std_logic_vector(1 downto 0);                     -- address
			POS_LIGNE_s1_readdata                    : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			SDRAM_s1_address                         : out std_logic_vector(23 downto 0);                    -- address
			SDRAM_s1_write                           : out std_logic;                                        -- write
			SDRAM_s1_read                            : out std_logic;                                        -- read
			SDRAM_s1_readdata                        : in  std_logic_vector(15 downto 0) := (others => 'X'); -- readdata
			SDRAM_s1_writedata                       : out std_logic_vector(15 downto 0);                    -- writedata
			SDRAM_s1_byteenable                      : out std_logic_vector(1 downto 0);                     -- byteenable
			SDRAM_s1_readdatavalid                   : in  std_logic                     := 'X';             -- readdatavalid
			SDRAM_s1_waitrequest                     : in  std_logic                     := 'X';             -- waitrequest
			SDRAM_s1_chipselect                      : out std_logic;                                        -- chipselect
			START_SL_s1_address                      : out std_logic_vector(1 downto 0);                     -- address
			START_SL_s1_write                        : out std_logic;                                        -- write
			START_SL_s1_readdata                     : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			START_SL_s1_writedata                    : out std_logic_vector(31 downto 0);                    -- writedata
			START_SL_s1_chipselect                   : out std_logic;                                        -- chipselect
			STATE_CRTL_s1_address                    : out std_logic_vector(1 downto 0);                     -- address
			STATE_CRTL_s1_readdata                   : in  std_logic_vector(31 downto 0) := (others => 'X'); -- readdata
			VECT_CAP_s1_address                      : out std_logic_vector(1 downto 0);                     -- address
			VECT_CAP_s1_readdata                     : in  std_logic_vector(31 downto 0) := (others => 'X')  -- readdata
		);
	end component nios_system_mm_interconnect_0;

	component nios_system_irq_mapper is
		port (
			clk           : in  std_logic                     := 'X'; -- clk
			reset         : in  std_logic                     := 'X'; -- reset
			receiver0_irq : in  std_logic                     := 'X'; -- irq
			sender_irq    : out std_logic_vector(31 downto 0)         -- irq
		);
	end component nios_system_irq_mapper;

	component altera_irq_clock_crosser is
		generic (
			IRQ_WIDTH : integer := 1
		);
		port (
			receiver_clk   : in  std_logic                    := 'X';             -- clk
			sender_clk     : in  std_logic                    := 'X';             -- clk
			receiver_reset : in  std_logic                    := 'X';             -- reset
			sender_reset   : in  std_logic                    := 'X';             -- reset
			receiver_irq   : in  std_logic_vector(0 downto 0) := (others => 'X'); -- irq
			sender_irq     : out std_logic_vector(0 downto 0)                     -- irq
		);
	end component altera_irq_clock_crosser;

	component nios_system_rst_controller is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			reset_in1      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component nios_system_rst_controller;

	component nios_system_rst_controller_001 is
		generic (
			NUM_RESET_INPUTS          : integer := 6;
			OUTPUT_RESET_SYNC_EDGES   : string  := "deassert";
			SYNC_DEPTH                : integer := 2;
			RESET_REQUEST_PRESENT     : integer := 0;
			RESET_REQ_WAIT_TIME       : integer := 1;
			MIN_RST_ASSERTION_TIME    : integer := 3;
			RESET_REQ_EARLY_DSRT_TIME : integer := 1;
			USE_RESET_REQUEST_IN0     : integer := 0;
			USE_RESET_REQUEST_IN1     : integer := 0;
			USE_RESET_REQUEST_IN2     : integer := 0;
			USE_RESET_REQUEST_IN3     : integer := 0;
			USE_RESET_REQUEST_IN4     : integer := 0;
			USE_RESET_REQUEST_IN5     : integer := 0;
			USE_RESET_REQUEST_IN6     : integer := 0;
			USE_RESET_REQUEST_IN7     : integer := 0;
			USE_RESET_REQUEST_IN8     : integer := 0;
			USE_RESET_REQUEST_IN9     : integer := 0;
			USE_RESET_REQUEST_IN10    : integer := 0;
			USE_RESET_REQUEST_IN11    : integer := 0;
			USE_RESET_REQUEST_IN12    : integer := 0;
			USE_RESET_REQUEST_IN13    : integer := 0;
			USE_RESET_REQUEST_IN14    : integer := 0;
			USE_RESET_REQUEST_IN15    : integer := 0;
			ADAPT_RESET_REQUEST       : integer := 0
		);
		port (
			reset_in0      : in  std_logic := 'X'; -- reset
			reset_in1      : in  std_logic := 'X'; -- reset
			clk            : in  std_logic := 'X'; -- clk
			reset_out      : out std_logic;        -- reset
			reset_req      : out std_logic;        -- reset_req
			reset_req_in0  : in  std_logic := 'X'; -- reset_req
			reset_req_in1  : in  std_logic := 'X'; -- reset_req
			reset_in2      : in  std_logic := 'X'; -- reset
			reset_req_in2  : in  std_logic := 'X'; -- reset_req
			reset_in3      : in  std_logic := 'X'; -- reset
			reset_req_in3  : in  std_logic := 'X'; -- reset_req
			reset_in4      : in  std_logic := 'X'; -- reset
			reset_req_in4  : in  std_logic := 'X'; -- reset_req
			reset_in5      : in  std_logic := 'X'; -- reset
			reset_req_in5  : in  std_logic := 'X'; -- reset_req
			reset_in6      : in  std_logic := 'X'; -- reset
			reset_req_in6  : in  std_logic := 'X'; -- reset_req
			reset_in7      : in  std_logic := 'X'; -- reset
			reset_req_in7  : in  std_logic := 'X'; -- reset_req
			reset_in8      : in  std_logic := 'X'; -- reset
			reset_req_in8  : in  std_logic := 'X'; -- reset_req
			reset_in9      : in  std_logic := 'X'; -- reset
			reset_req_in9  : in  std_logic := 'X'; -- reset_req
			reset_in10     : in  std_logic := 'X'; -- reset
			reset_req_in10 : in  std_logic := 'X'; -- reset_req
			reset_in11     : in  std_logic := 'X'; -- reset
			reset_req_in11 : in  std_logic := 'X'; -- reset_req
			reset_in12     : in  std_logic := 'X'; -- reset
			reset_req_in12 : in  std_logic := 'X'; -- reset_req
			reset_in13     : in  std_logic := 'X'; -- reset
			reset_req_in13 : in  std_logic := 'X'; -- reset_req
			reset_in14     : in  std_logic := 'X'; -- reset
			reset_req_in14 : in  std_logic := 'X'; -- reset_req
			reset_in15     : in  std_logic := 'X'; -- reset
			reset_req_in15 : in  std_logic := 'X'  -- reset_req
		);
	end component nios_system_rst_controller_001;

	signal clocks_sys_clk_clk                                            : std_logic;                     -- clocks:sys_clk -> [CNTRL_LEFT:clk, CNTRL_RIGHT:clk, CPU:clk, DATA_0R:clk, DATA_READY_R:clk, INPUT:clk, MEMOIRE_INTERNE:clk, NIVEAU:clk, POS_LIGNE:clk, SDRAM:clk, START_SL:clk, STATE_CRTL:clk, VECT_CAP:clk, irq_mapper:clk, irq_synchronizer:sender_clk, mm_interconnect_0:clocks_sys_clk_clk, rst_controller:clk]
	signal mm_interconnect_0_output_s1_writedata                         : std_logic_vector(31 downto 0); -- mm_interconnect_0:OUTPUT_s1_writedata -> OUTPUT:writedata
	signal mm_interconnect_0_output_s1_address                           : std_logic_vector(1 downto 0);  -- mm_interconnect_0:OUTPUT_s1_address -> OUTPUT:address
	signal mm_interconnect_0_output_s1_chipselect                        : std_logic;                     -- mm_interconnect_0:OUTPUT_s1_chipselect -> OUTPUT:chipselect
	signal mm_interconnect_0_output_s1_write                             : std_logic;                     -- mm_interconnect_0:OUTPUT_s1_write -> mm_interconnect_0_output_s1_write:in
	signal mm_interconnect_0_output_s1_readdata                          : std_logic_vector(31 downto 0); -- OUTPUT:readdata -> mm_interconnect_0:OUTPUT_s1_readdata
	signal mm_interconnect_0_data_ready_r_s1_address                     : std_logic_vector(1 downto 0);  -- mm_interconnect_0:DATA_READY_R_s1_address -> DATA_READY_R:address
	signal mm_interconnect_0_data_ready_r_s1_readdata                    : std_logic_vector(31 downto 0); -- DATA_READY_R:readdata -> mm_interconnect_0:DATA_READY_R_s1_readdata
	signal cpu_instruction_master_waitrequest                            : std_logic;                     -- mm_interconnect_0:CPU_instruction_master_waitrequest -> CPU:i_waitrequest
	signal cpu_instruction_master_address                                : std_logic_vector(26 downto 0); -- CPU:i_address -> mm_interconnect_0:CPU_instruction_master_address
	signal cpu_instruction_master_read                                   : std_logic;                     -- CPU:i_read -> mm_interconnect_0:CPU_instruction_master_read
	signal cpu_instruction_master_readdata                               : std_logic_vector(31 downto 0); -- mm_interconnect_0:CPU_instruction_master_readdata -> CPU:i_readdata
	signal mm_interconnect_0_cpu_jtag_debug_module_waitrequest           : std_logic;                     -- CPU:jtag_debug_module_waitrequest -> mm_interconnect_0:CPU_jtag_debug_module_waitrequest
	signal mm_interconnect_0_cpu_jtag_debug_module_writedata             : std_logic_vector(31 downto 0); -- mm_interconnect_0:CPU_jtag_debug_module_writedata -> CPU:jtag_debug_module_writedata
	signal mm_interconnect_0_cpu_jtag_debug_module_address               : std_logic_vector(8 downto 0);  -- mm_interconnect_0:CPU_jtag_debug_module_address -> CPU:jtag_debug_module_address
	signal mm_interconnect_0_cpu_jtag_debug_module_write                 : std_logic;                     -- mm_interconnect_0:CPU_jtag_debug_module_write -> CPU:jtag_debug_module_write
	signal mm_interconnect_0_cpu_jtag_debug_module_read                  : std_logic;                     -- mm_interconnect_0:CPU_jtag_debug_module_read -> CPU:jtag_debug_module_read
	signal mm_interconnect_0_cpu_jtag_debug_module_readdata              : std_logic_vector(31 downto 0); -- CPU:jtag_debug_module_readdata -> mm_interconnect_0:CPU_jtag_debug_module_readdata
	signal mm_interconnect_0_cpu_jtag_debug_module_debugaccess           : std_logic;                     -- mm_interconnect_0:CPU_jtag_debug_module_debugaccess -> CPU:jtag_debug_module_debugaccess
	signal mm_interconnect_0_cpu_jtag_debug_module_byteenable            : std_logic_vector(3 downto 0);  -- mm_interconnect_0:CPU_jtag_debug_module_byteenable -> CPU:jtag_debug_module_byteenable
	signal mm_interconnect_0_niveau_s1_writedata                         : std_logic_vector(31 downto 0); -- mm_interconnect_0:NIVEAU_s1_writedata -> NIVEAU:writedata
	signal mm_interconnect_0_niveau_s1_address                           : std_logic_vector(1 downto 0);  -- mm_interconnect_0:NIVEAU_s1_address -> NIVEAU:address
	signal mm_interconnect_0_niveau_s1_chipselect                        : std_logic;                     -- mm_interconnect_0:NIVEAU_s1_chipselect -> NIVEAU:chipselect
	signal mm_interconnect_0_niveau_s1_write                             : std_logic;                     -- mm_interconnect_0:NIVEAU_s1_write -> mm_interconnect_0_niveau_s1_write:in
	signal mm_interconnect_0_niveau_s1_readdata                          : std_logic_vector(31 downto 0); -- NIVEAU:readdata -> mm_interconnect_0:NIVEAU_s1_readdata
	signal cpu_data_master_waitrequest                                   : std_logic;                     -- mm_interconnect_0:CPU_data_master_waitrequest -> CPU:d_waitrequest
	signal cpu_data_master_writedata                                     : std_logic_vector(31 downto 0); -- CPU:d_writedata -> mm_interconnect_0:CPU_data_master_writedata
	signal cpu_data_master_address                                       : std_logic_vector(26 downto 0); -- CPU:d_address -> mm_interconnect_0:CPU_data_master_address
	signal cpu_data_master_write                                         : std_logic;                     -- CPU:d_write -> mm_interconnect_0:CPU_data_master_write
	signal cpu_data_master_read                                          : std_logic;                     -- CPU:d_read -> mm_interconnect_0:CPU_data_master_read
	signal cpu_data_master_readdata                                      : std_logic_vector(31 downto 0); -- mm_interconnect_0:CPU_data_master_readdata -> CPU:d_readdata
	signal cpu_data_master_debugaccess                                   : std_logic;                     -- CPU:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:CPU_data_master_debugaccess
	signal cpu_data_master_byteenable                                    : std_logic_vector(3 downto 0);  -- CPU:d_byteenable -> mm_interconnect_0:CPU_data_master_byteenable
	signal mm_interconnect_0_start_sl_s1_writedata                       : std_logic_vector(31 downto 0); -- mm_interconnect_0:START_SL_s1_writedata -> START_SL:writedata
	signal mm_interconnect_0_start_sl_s1_address                         : std_logic_vector(1 downto 0);  -- mm_interconnect_0:START_SL_s1_address -> START_SL:address
	signal mm_interconnect_0_start_sl_s1_chipselect                      : std_logic;                     -- mm_interconnect_0:START_SL_s1_chipselect -> START_SL:chipselect
	signal mm_interconnect_0_start_sl_s1_write                           : std_logic;                     -- mm_interconnect_0:START_SL_s1_write -> mm_interconnect_0_start_sl_s1_write:in
	signal mm_interconnect_0_start_sl_s1_readdata                        : std_logic_vector(31 downto 0); -- START_SL:readdata -> mm_interconnect_0:START_SL_s1_readdata
	signal mm_interconnect_0_sdram_s1_waitrequest                        : std_logic;                     -- SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	signal mm_interconnect_0_sdram_s1_writedata                          : std_logic_vector(15 downto 0); -- mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	signal mm_interconnect_0_sdram_s1_address                            : std_logic_vector(23 downto 0); -- mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	signal mm_interconnect_0_sdram_s1_chipselect                         : std_logic;                     -- mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	signal mm_interconnect_0_sdram_s1_write                              : std_logic;                     -- mm_interconnect_0:SDRAM_s1_write -> mm_interconnect_0_sdram_s1_write:in
	signal mm_interconnect_0_sdram_s1_read                               : std_logic;                     -- mm_interconnect_0:SDRAM_s1_read -> mm_interconnect_0_sdram_s1_read:in
	signal mm_interconnect_0_sdram_s1_readdata                           : std_logic_vector(15 downto 0); -- SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	signal mm_interconnect_0_sdram_s1_readdatavalid                      : std_logic;                     -- SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	signal mm_interconnect_0_sdram_s1_byteenable                         : std_logic_vector(1 downto 0);  -- mm_interconnect_0:SDRAM_s1_byteenable -> mm_interconnect_0_sdram_s1_byteenable:in
	signal mm_interconnect_0_vect_cap_s1_address                         : std_logic_vector(1 downto 0);  -- mm_interconnect_0:VECT_CAP_s1_address -> VECT_CAP:address
	signal mm_interconnect_0_vect_cap_s1_readdata                        : std_logic_vector(31 downto 0); -- VECT_CAP:readdata -> mm_interconnect_0:VECT_CAP_s1_readdata
	signal mm_interconnect_0_cntrl_left_s1_writedata                     : std_logic_vector(31 downto 0); -- mm_interconnect_0:CNTRL_LEFT_s1_writedata -> CNTRL_LEFT:writedata
	signal mm_interconnect_0_cntrl_left_s1_address                       : std_logic_vector(1 downto 0);  -- mm_interconnect_0:CNTRL_LEFT_s1_address -> CNTRL_LEFT:address
	signal mm_interconnect_0_cntrl_left_s1_chipselect                    : std_logic;                     -- mm_interconnect_0:CNTRL_LEFT_s1_chipselect -> CNTRL_LEFT:chipselect
	signal mm_interconnect_0_cntrl_left_s1_write                         : std_logic;                     -- mm_interconnect_0:CNTRL_LEFT_s1_write -> mm_interconnect_0_cntrl_left_s1_write:in
	signal mm_interconnect_0_cntrl_left_s1_readdata                      : std_logic_vector(31 downto 0); -- CNTRL_LEFT:readdata -> mm_interconnect_0:CNTRL_LEFT_s1_readdata
	signal mm_interconnect_0_memoire_interne_s1_writedata                : std_logic_vector(31 downto 0); -- mm_interconnect_0:MEMOIRE_INTERNE_s1_writedata -> MEMOIRE_INTERNE:writedata
	signal mm_interconnect_0_memoire_interne_s1_address                  : std_logic_vector(9 downto 0);  -- mm_interconnect_0:MEMOIRE_INTERNE_s1_address -> MEMOIRE_INTERNE:address
	signal mm_interconnect_0_memoire_interne_s1_chipselect               : std_logic;                     -- mm_interconnect_0:MEMOIRE_INTERNE_s1_chipselect -> MEMOIRE_INTERNE:chipselect
	signal mm_interconnect_0_memoire_interne_s1_clken                    : std_logic;                     -- mm_interconnect_0:MEMOIRE_INTERNE_s1_clken -> MEMOIRE_INTERNE:clken
	signal mm_interconnect_0_memoire_interne_s1_write                    : std_logic;                     -- mm_interconnect_0:MEMOIRE_INTERNE_s1_write -> MEMOIRE_INTERNE:write
	signal mm_interconnect_0_memoire_interne_s1_readdata                 : std_logic_vector(31 downto 0); -- MEMOIRE_INTERNE:readdata -> mm_interconnect_0:MEMOIRE_INTERNE_s1_readdata
	signal mm_interconnect_0_memoire_interne_s1_byteenable               : std_logic_vector(3 downto 0);  -- mm_interconnect_0:MEMOIRE_INTERNE_s1_byteenable -> MEMOIRE_INTERNE:byteenable
	signal mm_interconnect_0_data_0r_s1_address                          : std_logic_vector(1 downto 0);  -- mm_interconnect_0:DATA_0R_s1_address -> DATA_0R:address
	signal mm_interconnect_0_data_0r_s1_readdata                         : std_logic_vector(31 downto 0); -- DATA_0R:readdata -> mm_interconnect_0:DATA_0R_s1_readdata
	signal mm_interconnect_0_state_crtl_s1_address                       : std_logic_vector(1 downto 0);  -- mm_interconnect_0:STATE_CRTL_s1_address -> STATE_CRTL:address
	signal mm_interconnect_0_state_crtl_s1_readdata                      : std_logic_vector(31 downto 0); -- STATE_CRTL:readdata -> mm_interconnect_0:STATE_CRTL_s1_readdata
	signal mm_interconnect_0_cntrl_right_s1_writedata                    : std_logic_vector(31 downto 0); -- mm_interconnect_0:CNTRL_RIGHT_s1_writedata -> CNTRL_RIGHT:writedata
	signal mm_interconnect_0_cntrl_right_s1_address                      : std_logic_vector(1 downto 0);  -- mm_interconnect_0:CNTRL_RIGHT_s1_address -> CNTRL_RIGHT:address
	signal mm_interconnect_0_cntrl_right_s1_chipselect                   : std_logic;                     -- mm_interconnect_0:CNTRL_RIGHT_s1_chipselect -> CNTRL_RIGHT:chipselect
	signal mm_interconnect_0_cntrl_right_s1_write                        : std_logic;                     -- mm_interconnect_0:CNTRL_RIGHT_s1_write -> mm_interconnect_0_cntrl_right_s1_write:in
	signal mm_interconnect_0_cntrl_right_s1_readdata                     : std_logic_vector(31 downto 0); -- CNTRL_RIGHT:readdata -> mm_interconnect_0:CNTRL_RIGHT_s1_readdata
	signal mm_interconnect_0_input_s1_address                            : std_logic_vector(1 downto 0);  -- mm_interconnect_0:INPUT_s1_address -> INPUT:address
	signal mm_interconnect_0_input_s1_readdata                           : std_logic_vector(31 downto 0); -- INPUT:readdata -> mm_interconnect_0:INPUT_s1_readdata
	signal mm_interconnect_0_pos_ligne_s1_address                        : std_logic_vector(1 downto 0);  -- mm_interconnect_0:POS_LIGNE_s1_address -> POS_LIGNE:address
	signal mm_interconnect_0_pos_ligne_s1_readdata                       : std_logic_vector(31 downto 0); -- POS_LIGNE:readdata -> mm_interconnect_0:POS_LIGNE_s1_readdata
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest     : std_logic;                     -- JTAG_UART:av_waitrequest -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_waitrequest
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata       : std_logic_vector(31 downto 0); -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_writedata -> JTAG_UART:av_writedata
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_address         : std_logic_vector(0 downto 0);  -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_address -> JTAG_UART:av_address
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect      : std_logic;                     -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_chipselect -> JTAG_UART:av_chipselect
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_write           : std_logic;                     -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_write -> mm_interconnect_0_jtag_uart_avalon_jtag_slave_write:in
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_read            : std_logic;                     -- mm_interconnect_0:JTAG_UART_avalon_jtag_slave_read -> mm_interconnect_0_jtag_uart_avalon_jtag_slave_read:in
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata        : std_logic_vector(31 downto 0); -- JTAG_UART:av_readdata -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_readdata
	signal cpu_d_irq_irq                                                 : std_logic_vector(31 downto 0); -- irq_mapper:sender_irq -> CPU:d_irq
	signal irq_mapper_receiver0_irq                                      : std_logic;                     -- irq_synchronizer:sender_irq -> irq_mapper:receiver0_irq
	signal irq_synchronizer_receiver_irq                                 : std_logic_vector(0 downto 0);  -- JTAG_UART:av_irq -> irq_synchronizer:receiver_irq
	signal rst_controller_reset_out_reset                                : std_logic;                     -- rst_controller:reset_out -> [MEMOIRE_INTERNE:reset, irq_mapper:reset, irq_synchronizer:sender_reset, mm_interconnect_0:CPU_reset_n_reset_bridge_in_reset_reset, rst_controller_reset_out_reset:in, rst_translator:in_reset]
	signal rst_controller_reset_out_reset_req                            : std_logic;                     -- rst_controller:reset_req -> [CPU:reset_req, MEMOIRE_INTERNE:reset_req, rst_translator:reset_req_in]
	signal cpu_jtag_debug_module_reset_reset                             : std_logic;                     -- CPU:jtag_debug_module_resetrequest -> [rst_controller:reset_in1, rst_controller_001:reset_in1]
	signal rst_controller_001_reset_out_reset                            : std_logic;                     -- rst_controller_001:reset_out -> [clocks:reset, irq_synchronizer:receiver_reset, mm_interconnect_0:OUTPUT_reset_reset_bridge_in_reset_reset, rst_controller_001_reset_out_reset:in]
	signal reset_reset_n_ports_inv                                       : std_logic;                     -- reset_reset_n:inv -> [rst_controller:reset_in0, rst_controller_001:reset_in0]
	signal mm_interconnect_0_output_s1_write_ports_inv                   : std_logic;                     -- mm_interconnect_0_output_s1_write:inv -> OUTPUT:write_n
	signal mm_interconnect_0_niveau_s1_write_ports_inv                   : std_logic;                     -- mm_interconnect_0_niveau_s1_write:inv -> NIVEAU:write_n
	signal mm_interconnect_0_start_sl_s1_write_ports_inv                 : std_logic;                     -- mm_interconnect_0_start_sl_s1_write:inv -> START_SL:write_n
	signal mm_interconnect_0_sdram_s1_write_ports_inv                    : std_logic;                     -- mm_interconnect_0_sdram_s1_write:inv -> SDRAM:az_wr_n
	signal mm_interconnect_0_sdram_s1_read_ports_inv                     : std_logic;                     -- mm_interconnect_0_sdram_s1_read:inv -> SDRAM:az_rd_n
	signal mm_interconnect_0_sdram_s1_byteenable_ports_inv               : std_logic_vector(1 downto 0);  -- mm_interconnect_0_sdram_s1_byteenable:inv -> SDRAM:az_be_n
	signal mm_interconnect_0_cntrl_left_s1_write_ports_inv               : std_logic;                     -- mm_interconnect_0_cntrl_left_s1_write:inv -> CNTRL_LEFT:write_n
	signal mm_interconnect_0_cntrl_right_s1_write_ports_inv              : std_logic;                     -- mm_interconnect_0_cntrl_right_s1_write:inv -> CNTRL_RIGHT:write_n
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv : std_logic;                     -- mm_interconnect_0_jtag_uart_avalon_jtag_slave_write:inv -> JTAG_UART:av_write_n
	signal mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv  : std_logic;                     -- mm_interconnect_0_jtag_uart_avalon_jtag_slave_read:inv -> JTAG_UART:av_read_n
	signal rst_controller_reset_out_reset_ports_inv                      : std_logic;                     -- rst_controller_reset_out_reset:inv -> [CNTRL_LEFT:reset_n, CNTRL_RIGHT:reset_n, CPU:reset_n, DATA_0R:reset_n, DATA_READY_R:reset_n, INPUT:reset_n, NIVEAU:reset_n, POS_LIGNE:reset_n, SDRAM:reset_n, START_SL:reset_n, STATE_CRTL:reset_n, VECT_CAP:reset_n]
	signal rst_controller_001_reset_out_reset_ports_inv                  : std_logic;                     -- rst_controller_001_reset_out_reset:inv -> [JTAG_UART:rst_n, OUTPUT:reset_n]

begin

	cpu : component nios_system_CPU
		port map (
			clk                                   => clocks_sys_clk_clk,                                  --                       clk.clk
			reset_n                               => rst_controller_reset_out_reset_ports_inv,            --                   reset_n.reset_n
			reset_req                             => rst_controller_reset_out_reset_req,                  --                          .reset_req
			d_address                             => cpu_data_master_address,                             --               data_master.address
			d_byteenable                          => cpu_data_master_byteenable,                          --                          .byteenable
			d_read                                => cpu_data_master_read,                                --                          .read
			d_readdata                            => cpu_data_master_readdata,                            --                          .readdata
			d_waitrequest                         => cpu_data_master_waitrequest,                         --                          .waitrequest
			d_write                               => cpu_data_master_write,                               --                          .write
			d_writedata                           => cpu_data_master_writedata,                           --                          .writedata
			jtag_debug_module_debugaccess_to_roms => cpu_data_master_debugaccess,                         --                          .debugaccess
			i_address                             => cpu_instruction_master_address,                      --        instruction_master.address
			i_read                                => cpu_instruction_master_read,                         --                          .read
			i_readdata                            => cpu_instruction_master_readdata,                     --                          .readdata
			i_waitrequest                         => cpu_instruction_master_waitrequest,                  --                          .waitrequest
			d_irq                                 => cpu_d_irq_irq,                                       --                     d_irq.irq
			jtag_debug_module_resetrequest        => cpu_jtag_debug_module_reset_reset,                   --   jtag_debug_module_reset.reset
			jtag_debug_module_address             => mm_interconnect_0_cpu_jtag_debug_module_address,     --         jtag_debug_module.address
			jtag_debug_module_byteenable          => mm_interconnect_0_cpu_jtag_debug_module_byteenable,  --                          .byteenable
			jtag_debug_module_debugaccess         => mm_interconnect_0_cpu_jtag_debug_module_debugaccess, --                          .debugaccess
			jtag_debug_module_read                => mm_interconnect_0_cpu_jtag_debug_module_read,        --                          .read
			jtag_debug_module_readdata            => mm_interconnect_0_cpu_jtag_debug_module_readdata,    --                          .readdata
			jtag_debug_module_waitrequest         => mm_interconnect_0_cpu_jtag_debug_module_waitrequest, --                          .waitrequest
			jtag_debug_module_write               => mm_interconnect_0_cpu_jtag_debug_module_write,       --                          .write
			jtag_debug_module_writedata           => mm_interconnect_0_cpu_jtag_debug_module_writedata,   --                          .writedata
			no_ci_readra                          => open                                                 -- custom_instruction_master.readra
		);

	memoire_interne : component nios_system_MEMOIRE_INTERNE
		port map (
			clk        => clocks_sys_clk_clk,                              --   clk1.clk
			address    => mm_interconnect_0_memoire_interne_s1_address,    --     s1.address
			clken      => mm_interconnect_0_memoire_interne_s1_clken,      --       .clken
			chipselect => mm_interconnect_0_memoire_interne_s1_chipselect, --       .chipselect
			write      => mm_interconnect_0_memoire_interne_s1_write,      --       .write
			readdata   => mm_interconnect_0_memoire_interne_s1_readdata,   --       .readdata
			writedata  => mm_interconnect_0_memoire_interne_s1_writedata,  --       .writedata
			byteenable => mm_interconnect_0_memoire_interne_s1_byteenable, --       .byteenable
			reset      => rst_controller_reset_out_reset,                  -- reset1.reset
			reset_req  => rst_controller_reset_out_reset_req               --       .reset_req
		);

	input : component nios_system_INPUT
		port map (
			clk      => clocks_sys_clk_clk,                       --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv, --               reset.reset_n
			address  => mm_interconnect_0_input_s1_address,       --                  s1.address
			readdata => mm_interconnect_0_input_s1_readdata,      --                    .readdata
			in_port  => switches_export                           -- external_connection.export
		);

	output : component nios_system_OUTPUT
		port map (
			clk        => clk_clk,                                      --                 clk.clk
			reset_n    => rst_controller_001_reset_out_reset_ports_inv, --               reset.reset_n
			address    => mm_interconnect_0_output_s1_address,          --                  s1.address
			write_n    => mm_interconnect_0_output_s1_write_ports_inv,  --                    .write_n
			writedata  => mm_interconnect_0_output_s1_writedata,        --                    .writedata
			chipselect => mm_interconnect_0_output_s1_chipselect,       --                    .chipselect
			readdata   => mm_interconnect_0_output_s1_readdata,         --                    .readdata
			out_port   => leds_export                                   -- external_connection.export
		);

	jtag_uart : component nios_system_JTAG_UART
		port map (
			clk            => clk_clk,                                                       --               clk.clk
			rst_n          => rst_controller_001_reset_out_reset_ports_inv,                  --             reset.reset_n
			av_chipselect  => mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect,      -- avalon_jtag_slave.chipselect
			av_address     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_address(0),      --                  .address
			av_read_n      => mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv,  --                  .read_n
			av_readdata    => mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata,        --                  .readdata
			av_write_n     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv, --                  .write_n
			av_writedata   => mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata,       --                  .writedata
			av_waitrequest => mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest,     --                  .waitrequest
			av_irq         => irq_synchronizer_receiver_irq(0)                               --               irq.irq
		);

	sdram : component nios_system_SDRAM
		port map (
			clk            => clocks_sys_clk_clk,                              --   clk.clk
			reset_n        => rst_controller_reset_out_reset_ports_inv,        -- reset.reset_n
			az_addr        => mm_interconnect_0_sdram_s1_address,              --    s1.address
			az_be_n        => mm_interconnect_0_sdram_s1_byteenable_ports_inv, --      .byteenable_n
			az_cs          => mm_interconnect_0_sdram_s1_chipselect,           --      .chipselect
			az_data        => mm_interconnect_0_sdram_s1_writedata,            --      .writedata
			az_rd_n        => mm_interconnect_0_sdram_s1_read_ports_inv,       --      .read_n
			az_wr_n        => mm_interconnect_0_sdram_s1_write_ports_inv,      --      .write_n
			za_data        => mm_interconnect_0_sdram_s1_readdata,             --      .readdata
			za_valid       => mm_interconnect_0_sdram_s1_readdatavalid,        --      .readdatavalid
			za_waitrequest => mm_interconnect_0_sdram_s1_waitrequest,          --      .waitrequest
			zs_addr        => sdram_wire_addr,                                 --  wire.export
			zs_ba          => sdram_wire_ba,                                   --      .export
			zs_cas_n       => sdram_wire_cas_n,                                --      .export
			zs_cke         => sdram_wire_cke,                                  --      .export
			zs_cs_n        => sdram_wire_cs_n,                                 --      .export
			zs_dq          => sdram_wire_dq,                                   --      .export
			zs_dqm         => sdram_wire_dqm,                                  --      .export
			zs_ras_n       => sdram_wire_ras_n,                                --      .export
			zs_we_n        => sdram_wire_we_n                                  --      .export
		);

	cntrl_left : component nios_system_CNTRL_LEFT
		port map (
			clk        => clocks_sys_clk_clk,                              --                 clk.clk
			reset_n    => rst_controller_reset_out_reset_ports_inv,        --               reset.reset_n
			address    => mm_interconnect_0_cntrl_left_s1_address,         --                  s1.address
			write_n    => mm_interconnect_0_cntrl_left_s1_write_ports_inv, --                    .write_n
			writedata  => mm_interconnect_0_cntrl_left_s1_writedata,       --                    .writedata
			chipselect => mm_interconnect_0_cntrl_left_s1_chipselect,      --                    .chipselect
			readdata   => mm_interconnect_0_cntrl_left_s1_readdata,        --                    .readdata
			out_port   => cntrl_left_export                                -- external_connection.export
		);

	cntrl_right : component nios_system_CNTRL_LEFT
		port map (
			clk        => clocks_sys_clk_clk,                               --                 clk.clk
			reset_n    => rst_controller_reset_out_reset_ports_inv,         --               reset.reset_n
			address    => mm_interconnect_0_cntrl_right_s1_address,         --                  s1.address
			write_n    => mm_interconnect_0_cntrl_right_s1_write_ports_inv, --                    .write_n
			writedata  => mm_interconnect_0_cntrl_right_s1_writedata,       --                    .writedata
			chipselect => mm_interconnect_0_cntrl_right_s1_chipselect,      --                    .chipselect
			readdata   => mm_interconnect_0_cntrl_right_s1_readdata,        --                    .readdata
			out_port   => cntrl_right_export                                -- external_connection.export
		);

	data_0r : component nios_system_INPUT
		port map (
			clk      => clocks_sys_clk_clk,                       --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv, --               reset.reset_n
			address  => mm_interconnect_0_data_0r_s1_address,     --                  s1.address
			readdata => mm_interconnect_0_data_0r_s1_readdata,    --                    .readdata
			in_port  => data_0r_external_connection_export        -- external_connection.export
		);

	data_ready_r : component nios_system_DATA_READY_R
		port map (
			clk      => clocks_sys_clk_clk,                         --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv,   --               reset.reset_n
			address  => mm_interconnect_0_data_ready_r_s1_address,  --                  s1.address
			readdata => mm_interconnect_0_data_ready_r_s1_readdata, --                    .readdata
			in_port  => data_ready_r_external_connection_export     -- external_connection.export
		);

	vect_cap : component nios_system_VECT_CAP
		port map (
			clk      => clocks_sys_clk_clk,                       --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv, --               reset.reset_n
			address  => mm_interconnect_0_vect_cap_s1_address,    --                  s1.address
			readdata => mm_interconnect_0_vect_cap_s1_readdata,   --                    .readdata
			in_port  => vect_cap_external_connection_export       -- external_connection.export
		);

	niveau : component nios_system_OUTPUT
		port map (
			clk        => clocks_sys_clk_clk,                          --                 clk.clk
			reset_n    => rst_controller_reset_out_reset_ports_inv,    --               reset.reset_n
			address    => mm_interconnect_0_niveau_s1_address,         --                  s1.address
			write_n    => mm_interconnect_0_niveau_s1_write_ports_inv, --                    .write_n
			writedata  => mm_interconnect_0_niveau_s1_writedata,       --                    .writedata
			chipselect => mm_interconnect_0_niveau_s1_chipselect,      --                    .chipselect
			readdata   => mm_interconnect_0_niveau_s1_readdata,        --                    .readdata
			out_port   => niveau_external_connection_export            -- external_connection.export
		);

	start_sl : component nios_system_START_SL
		port map (
			clk        => clocks_sys_clk_clk,                            --                 clk.clk
			reset_n    => rst_controller_reset_out_reset_ports_inv,      --               reset.reset_n
			address    => mm_interconnect_0_start_sl_s1_address,         --                  s1.address
			write_n    => mm_interconnect_0_start_sl_s1_write_ports_inv, --                    .write_n
			writedata  => mm_interconnect_0_start_sl_s1_writedata,       --                    .writedata
			chipselect => mm_interconnect_0_start_sl_s1_chipselect,      --                    .chipselect
			readdata   => mm_interconnect_0_start_sl_s1_readdata,        --                    .readdata
			out_port   => start_sl_external_connection_export            -- external_connection.export
		);

	pos_ligne : component nios_system_POS_LIGNE
		port map (
			clk      => clocks_sys_clk_clk,                       --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv, --               reset.reset_n
			address  => mm_interconnect_0_pos_ligne_s1_address,   --                  s1.address
			readdata => mm_interconnect_0_pos_ligne_s1_readdata,  --                    .readdata
			in_port  => pos_ligne_external_connection_export      -- external_connection.export
		);

	state_crtl : component nios_system_STATE_CRTL
		port map (
			clk      => clocks_sys_clk_clk,                       --                 clk.clk
			reset_n  => rst_controller_reset_out_reset_ports_inv, --               reset.reset_n
			address  => mm_interconnect_0_state_crtl_s1_address,  --                  s1.address
			readdata => mm_interconnect_0_state_crtl_s1_readdata, --                    .readdata
			in_port  => state_crtl_external_connection_export     -- external_connection.export
		);

	clocks : component nios_system_clocks
		port map (
			CLOCK_50    => clk_clk,                            --       clk_in_primary.clk
			reset       => rst_controller_001_reset_out_reset, -- clk_in_primary_reset.reset
			sys_clk     => clocks_sys_clk_clk,                 --              sys_clk.clk
			sys_reset_n => open,                               --        sys_clk_reset.reset_n
			SDRAM_CLK   => sdram_clk_clk                       --            sdram_clk.clk
		);

	mm_interconnect_0 : component nios_system_mm_interconnect_0
		port map (
			clk_0_clk_clk                            => clk_clk,                                                   --                          clk_0_clk.clk
			clocks_sys_clk_clk                       => clocks_sys_clk_clk,                                        --                     clocks_sys_clk.clk
			CPU_reset_n_reset_bridge_in_reset_reset  => rst_controller_reset_out_reset,                            --  CPU_reset_n_reset_bridge_in_reset.reset
			OUTPUT_reset_reset_bridge_in_reset_reset => rst_controller_001_reset_out_reset,                        -- OUTPUT_reset_reset_bridge_in_reset.reset
			CPU_data_master_address                  => cpu_data_master_address,                                   --                    CPU_data_master.address
			CPU_data_master_waitrequest              => cpu_data_master_waitrequest,                               --                                   .waitrequest
			CPU_data_master_byteenable               => cpu_data_master_byteenable,                                --                                   .byteenable
			CPU_data_master_read                     => cpu_data_master_read,                                      --                                   .read
			CPU_data_master_readdata                 => cpu_data_master_readdata,                                  --                                   .readdata
			CPU_data_master_write                    => cpu_data_master_write,                                     --                                   .write
			CPU_data_master_writedata                => cpu_data_master_writedata,                                 --                                   .writedata
			CPU_data_master_debugaccess              => cpu_data_master_debugaccess,                               --                                   .debugaccess
			CPU_instruction_master_address           => cpu_instruction_master_address,                            --             CPU_instruction_master.address
			CPU_instruction_master_waitrequest       => cpu_instruction_master_waitrequest,                        --                                   .waitrequest
			CPU_instruction_master_read              => cpu_instruction_master_read,                               --                                   .read
			CPU_instruction_master_readdata          => cpu_instruction_master_readdata,                           --                                   .readdata
			CNTRL_LEFT_s1_address                    => mm_interconnect_0_cntrl_left_s1_address,                   --                      CNTRL_LEFT_s1.address
			CNTRL_LEFT_s1_write                      => mm_interconnect_0_cntrl_left_s1_write,                     --                                   .write
			CNTRL_LEFT_s1_readdata                   => mm_interconnect_0_cntrl_left_s1_readdata,                  --                                   .readdata
			CNTRL_LEFT_s1_writedata                  => mm_interconnect_0_cntrl_left_s1_writedata,                 --                                   .writedata
			CNTRL_LEFT_s1_chipselect                 => mm_interconnect_0_cntrl_left_s1_chipselect,                --                                   .chipselect
			CNTRL_RIGHT_s1_address                   => mm_interconnect_0_cntrl_right_s1_address,                  --                     CNTRL_RIGHT_s1.address
			CNTRL_RIGHT_s1_write                     => mm_interconnect_0_cntrl_right_s1_write,                    --                                   .write
			CNTRL_RIGHT_s1_readdata                  => mm_interconnect_0_cntrl_right_s1_readdata,                 --                                   .readdata
			CNTRL_RIGHT_s1_writedata                 => mm_interconnect_0_cntrl_right_s1_writedata,                --                                   .writedata
			CNTRL_RIGHT_s1_chipselect                => mm_interconnect_0_cntrl_right_s1_chipselect,               --                                   .chipselect
			CPU_jtag_debug_module_address            => mm_interconnect_0_cpu_jtag_debug_module_address,           --              CPU_jtag_debug_module.address
			CPU_jtag_debug_module_write              => mm_interconnect_0_cpu_jtag_debug_module_write,             --                                   .write
			CPU_jtag_debug_module_read               => mm_interconnect_0_cpu_jtag_debug_module_read,              --                                   .read
			CPU_jtag_debug_module_readdata           => mm_interconnect_0_cpu_jtag_debug_module_readdata,          --                                   .readdata
			CPU_jtag_debug_module_writedata          => mm_interconnect_0_cpu_jtag_debug_module_writedata,         --                                   .writedata
			CPU_jtag_debug_module_byteenable         => mm_interconnect_0_cpu_jtag_debug_module_byteenable,        --                                   .byteenable
			CPU_jtag_debug_module_waitrequest        => mm_interconnect_0_cpu_jtag_debug_module_waitrequest,       --                                   .waitrequest
			CPU_jtag_debug_module_debugaccess        => mm_interconnect_0_cpu_jtag_debug_module_debugaccess,       --                                   .debugaccess
			DATA_0R_s1_address                       => mm_interconnect_0_data_0r_s1_address,                      --                         DATA_0R_s1.address
			DATA_0R_s1_readdata                      => mm_interconnect_0_data_0r_s1_readdata,                     --                                   .readdata
			DATA_READY_R_s1_address                  => mm_interconnect_0_data_ready_r_s1_address,                 --                    DATA_READY_R_s1.address
			DATA_READY_R_s1_readdata                 => mm_interconnect_0_data_ready_r_s1_readdata,                --                                   .readdata
			INPUT_s1_address                         => mm_interconnect_0_input_s1_address,                        --                           INPUT_s1.address
			INPUT_s1_readdata                        => mm_interconnect_0_input_s1_readdata,                       --                                   .readdata
			JTAG_UART_avalon_jtag_slave_address      => mm_interconnect_0_jtag_uart_avalon_jtag_slave_address,     --        JTAG_UART_avalon_jtag_slave.address
			JTAG_UART_avalon_jtag_slave_write        => mm_interconnect_0_jtag_uart_avalon_jtag_slave_write,       --                                   .write
			JTAG_UART_avalon_jtag_slave_read         => mm_interconnect_0_jtag_uart_avalon_jtag_slave_read,        --                                   .read
			JTAG_UART_avalon_jtag_slave_readdata     => mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata,    --                                   .readdata
			JTAG_UART_avalon_jtag_slave_writedata    => mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata,   --                                   .writedata
			JTAG_UART_avalon_jtag_slave_waitrequest  => mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest, --                                   .waitrequest
			JTAG_UART_avalon_jtag_slave_chipselect   => mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect,  --                                   .chipselect
			MEMOIRE_INTERNE_s1_address               => mm_interconnect_0_memoire_interne_s1_address,              --                 MEMOIRE_INTERNE_s1.address
			MEMOIRE_INTERNE_s1_write                 => mm_interconnect_0_memoire_interne_s1_write,                --                                   .write
			MEMOIRE_INTERNE_s1_readdata              => mm_interconnect_0_memoire_interne_s1_readdata,             --                                   .readdata
			MEMOIRE_INTERNE_s1_writedata             => mm_interconnect_0_memoire_interne_s1_writedata,            --                                   .writedata
			MEMOIRE_INTERNE_s1_byteenable            => mm_interconnect_0_memoire_interne_s1_byteenable,           --                                   .byteenable
			MEMOIRE_INTERNE_s1_chipselect            => mm_interconnect_0_memoire_interne_s1_chipselect,           --                                   .chipselect
			MEMOIRE_INTERNE_s1_clken                 => mm_interconnect_0_memoire_interne_s1_clken,                --                                   .clken
			NIVEAU_s1_address                        => mm_interconnect_0_niveau_s1_address,                       --                          NIVEAU_s1.address
			NIVEAU_s1_write                          => mm_interconnect_0_niveau_s1_write,                         --                                   .write
			NIVEAU_s1_readdata                       => mm_interconnect_0_niveau_s1_readdata,                      --                                   .readdata
			NIVEAU_s1_writedata                      => mm_interconnect_0_niveau_s1_writedata,                     --                                   .writedata
			NIVEAU_s1_chipselect                     => mm_interconnect_0_niveau_s1_chipselect,                    --                                   .chipselect
			OUTPUT_s1_address                        => mm_interconnect_0_output_s1_address,                       --                          OUTPUT_s1.address
			OUTPUT_s1_write                          => mm_interconnect_0_output_s1_write,                         --                                   .write
			OUTPUT_s1_readdata                       => mm_interconnect_0_output_s1_readdata,                      --                                   .readdata
			OUTPUT_s1_writedata                      => mm_interconnect_0_output_s1_writedata,                     --                                   .writedata
			OUTPUT_s1_chipselect                     => mm_interconnect_0_output_s1_chipselect,                    --                                   .chipselect
			POS_LIGNE_s1_address                     => mm_interconnect_0_pos_ligne_s1_address,                    --                       POS_LIGNE_s1.address
			POS_LIGNE_s1_readdata                    => mm_interconnect_0_pos_ligne_s1_readdata,                   --                                   .readdata
			SDRAM_s1_address                         => mm_interconnect_0_sdram_s1_address,                        --                           SDRAM_s1.address
			SDRAM_s1_write                           => mm_interconnect_0_sdram_s1_write,                          --                                   .write
			SDRAM_s1_read                            => mm_interconnect_0_sdram_s1_read,                           --                                   .read
			SDRAM_s1_readdata                        => mm_interconnect_0_sdram_s1_readdata,                       --                                   .readdata
			SDRAM_s1_writedata                       => mm_interconnect_0_sdram_s1_writedata,                      --                                   .writedata
			SDRAM_s1_byteenable                      => mm_interconnect_0_sdram_s1_byteenable,                     --                                   .byteenable
			SDRAM_s1_readdatavalid                   => mm_interconnect_0_sdram_s1_readdatavalid,                  --                                   .readdatavalid
			SDRAM_s1_waitrequest                     => mm_interconnect_0_sdram_s1_waitrequest,                    --                                   .waitrequest
			SDRAM_s1_chipselect                      => mm_interconnect_0_sdram_s1_chipselect,                     --                                   .chipselect
			START_SL_s1_address                      => mm_interconnect_0_start_sl_s1_address,                     --                        START_SL_s1.address
			START_SL_s1_write                        => mm_interconnect_0_start_sl_s1_write,                       --                                   .write
			START_SL_s1_readdata                     => mm_interconnect_0_start_sl_s1_readdata,                    --                                   .readdata
			START_SL_s1_writedata                    => mm_interconnect_0_start_sl_s1_writedata,                   --                                   .writedata
			START_SL_s1_chipselect                   => mm_interconnect_0_start_sl_s1_chipselect,                  --                                   .chipselect
			STATE_CRTL_s1_address                    => mm_interconnect_0_state_crtl_s1_address,                   --                      STATE_CRTL_s1.address
			STATE_CRTL_s1_readdata                   => mm_interconnect_0_state_crtl_s1_readdata,                  --                                   .readdata
			VECT_CAP_s1_address                      => mm_interconnect_0_vect_cap_s1_address,                     --                        VECT_CAP_s1.address
			VECT_CAP_s1_readdata                     => mm_interconnect_0_vect_cap_s1_readdata                     --                                   .readdata
		);

	irq_mapper : component nios_system_irq_mapper
		port map (
			clk           => clocks_sys_clk_clk,             --       clk.clk
			reset         => rst_controller_reset_out_reset, -- clk_reset.reset
			receiver0_irq => irq_mapper_receiver0_irq,       -- receiver0.irq
			sender_irq    => cpu_d_irq_irq                   --    sender.irq
		);

	irq_synchronizer : component altera_irq_clock_crosser
		generic map (
			IRQ_WIDTH => 1
		)
		port map (
			receiver_clk   => clk_clk,                            --       receiver_clk.clk
			sender_clk     => clocks_sys_clk_clk,                 --         sender_clk.clk
			receiver_reset => rst_controller_001_reset_out_reset, -- receiver_clk_reset.reset
			sender_reset   => rst_controller_reset_out_reset,     --   sender_clk_reset.reset
			receiver_irq   => irq_synchronizer_receiver_irq,      --           receiver.irq
			sender_irq(0)  => irq_mapper_receiver0_irq            --             sender.irq
		);

	rst_controller : component nios_system_rst_controller
		generic map (
			NUM_RESET_INPUTS          => 2,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 1,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset_n_ports_inv,            -- reset_in0.reset
			reset_in1      => cpu_jtag_debug_module_reset_reset,  -- reset_in1.reset
			clk            => clocks_sys_clk_clk,                 --       clk.clk
			reset_out      => rst_controller_reset_out_reset,     -- reset_out.reset
			reset_req      => rst_controller_reset_out_reset_req, --          .reset_req
			reset_req_in0  => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

	rst_controller_001 : component nios_system_rst_controller_001
		generic map (
			NUM_RESET_INPUTS          => 2,
			OUTPUT_RESET_SYNC_EDGES   => "deassert",
			SYNC_DEPTH                => 2,
			RESET_REQUEST_PRESENT     => 0,
			RESET_REQ_WAIT_TIME       => 1,
			MIN_RST_ASSERTION_TIME    => 3,
			RESET_REQ_EARLY_DSRT_TIME => 1,
			USE_RESET_REQUEST_IN0     => 0,
			USE_RESET_REQUEST_IN1     => 0,
			USE_RESET_REQUEST_IN2     => 0,
			USE_RESET_REQUEST_IN3     => 0,
			USE_RESET_REQUEST_IN4     => 0,
			USE_RESET_REQUEST_IN5     => 0,
			USE_RESET_REQUEST_IN6     => 0,
			USE_RESET_REQUEST_IN7     => 0,
			USE_RESET_REQUEST_IN8     => 0,
			USE_RESET_REQUEST_IN9     => 0,
			USE_RESET_REQUEST_IN10    => 0,
			USE_RESET_REQUEST_IN11    => 0,
			USE_RESET_REQUEST_IN12    => 0,
			USE_RESET_REQUEST_IN13    => 0,
			USE_RESET_REQUEST_IN14    => 0,
			USE_RESET_REQUEST_IN15    => 0,
			ADAPT_RESET_REQUEST       => 0
		)
		port map (
			reset_in0      => reset_reset_n_ports_inv,            -- reset_in0.reset
			reset_in1      => cpu_jtag_debug_module_reset_reset,  -- reset_in1.reset
			clk            => clk_clk,                            --       clk.clk
			reset_out      => rst_controller_001_reset_out_reset, -- reset_out.reset
			reset_req      => open,                               -- (terminated)
			reset_req_in0  => '0',                                -- (terminated)
			reset_req_in1  => '0',                                -- (terminated)
			reset_in2      => '0',                                -- (terminated)
			reset_req_in2  => '0',                                -- (terminated)
			reset_in3      => '0',                                -- (terminated)
			reset_req_in3  => '0',                                -- (terminated)
			reset_in4      => '0',                                -- (terminated)
			reset_req_in4  => '0',                                -- (terminated)
			reset_in5      => '0',                                -- (terminated)
			reset_req_in5  => '0',                                -- (terminated)
			reset_in6      => '0',                                -- (terminated)
			reset_req_in6  => '0',                                -- (terminated)
			reset_in7      => '0',                                -- (terminated)
			reset_req_in7  => '0',                                -- (terminated)
			reset_in8      => '0',                                -- (terminated)
			reset_req_in8  => '0',                                -- (terminated)
			reset_in9      => '0',                                -- (terminated)
			reset_req_in9  => '0',                                -- (terminated)
			reset_in10     => '0',                                -- (terminated)
			reset_req_in10 => '0',                                -- (terminated)
			reset_in11     => '0',                                -- (terminated)
			reset_req_in11 => '0',                                -- (terminated)
			reset_in12     => '0',                                -- (terminated)
			reset_req_in12 => '0',                                -- (terminated)
			reset_in13     => '0',                                -- (terminated)
			reset_req_in13 => '0',                                -- (terminated)
			reset_in14     => '0',                                -- (terminated)
			reset_req_in14 => '0',                                -- (terminated)
			reset_in15     => '0',                                -- (terminated)
			reset_req_in15 => '0'                                 -- (terminated)
		);

	reset_reset_n_ports_inv <= not reset_reset_n;

	mm_interconnect_0_output_s1_write_ports_inv <= not mm_interconnect_0_output_s1_write;

	mm_interconnect_0_niveau_s1_write_ports_inv <= not mm_interconnect_0_niveau_s1_write;

	mm_interconnect_0_start_sl_s1_write_ports_inv <= not mm_interconnect_0_start_sl_s1_write;

	mm_interconnect_0_sdram_s1_write_ports_inv <= not mm_interconnect_0_sdram_s1_write;

	mm_interconnect_0_sdram_s1_read_ports_inv <= not mm_interconnect_0_sdram_s1_read;

	mm_interconnect_0_sdram_s1_byteenable_ports_inv <= not mm_interconnect_0_sdram_s1_byteenable;

	mm_interconnect_0_cntrl_left_s1_write_ports_inv <= not mm_interconnect_0_cntrl_left_s1_write;

	mm_interconnect_0_cntrl_right_s1_write_ports_inv <= not mm_interconnect_0_cntrl_right_s1_write;

	mm_interconnect_0_jtag_uart_avalon_jtag_slave_write_ports_inv <= not mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;

	mm_interconnect_0_jtag_uart_avalon_jtag_slave_read_ports_inv <= not mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;

	rst_controller_reset_out_reset_ports_inv <= not rst_controller_reset_out_reset;

	rst_controller_001_reset_out_reset_ports_inv <= not rst_controller_001_reset_out_reset;

end architecture rtl; -- of nios_system
