// nios_system.v

// Generated using ACDS version 13.1 162 at 2026.03.20.10:35:55

`timescale 1 ps / 1 ps
module nios_system (
		input  wire        clk_clk,                                 //                              clk.clk
		input  wire        reset_reset_n,                           //                            reset.reset_n
		input  wire [7:0]  switches_export,                         //                         switches.export
		output wire [7:0]  leds_export,                             //                             leds.export
		output wire [12:0] sdram_wire_addr,                         //                       sdram_wire.addr
		output wire [1:0]  sdram_wire_ba,                           //                                 .ba
		output wire        sdram_wire_cas_n,                        //                                 .cas_n
		output wire        sdram_wire_cke,                          //                                 .cke
		output wire        sdram_wire_cs_n,                         //                                 .cs_n
		inout  wire [15:0] sdram_wire_dq,                           //                                 .dq
		output wire [1:0]  sdram_wire_dqm,                          //                                 .dqm
		output wire        sdram_wire_ras_n,                        //                                 .ras_n
		output wire        sdram_wire_we_n,                         //                                 .we_n
		output wire [15:0] cntrl_left_export,                       //                       cntrl_left.export
		output wire [15:0] cntrl_right_export,                      //                      cntrl_right.export
		input  wire [7:0]  data_0r_external_connection_export,      //      data_0r_external_connection.export
		input  wire        data_ready_r_external_connection_export, // data_ready_r_external_connection.export
		input  wire [6:0]  vect_cap_external_connection_export,     //     vect_cap_external_connection.export
		output wire [7:0]  niveau_external_connection_export,       //       niveau_external_connection.export
		output wire        start_sl_external_connection_export,     //     start_sl_external_connection.export
		input  wire [3:0]  pos_ligne_external_connection_export,    //    pos_ligne_external_connection.export
		input  wire [1:0]  state_crtl_external_connection_export,   //   state_crtl_external_connection.export
		output wire        sdram_clk_clk                            //                        sdram_clk.clk
	);

	wire         clocks_sys_clk_clk;                                        // clocks:sys_clk -> [CNTRL_LEFT:clk, CNTRL_RIGHT:clk, CPU:clk, DATA_0R:clk, DATA_READY_R:clk, INPUT:clk, MEMOIRE_INTERNE:clk, NIVEAU:clk, POS_LIGNE:clk, SDRAM:clk, START_SL:clk, STATE_CRTL:clk, VECT_CAP:clk, irq_mapper:clk, irq_synchronizer:sender_clk, mm_interconnect_0:clocks_sys_clk_clk, rst_controller:clk]
	wire   [1:0] mm_interconnect_0_pos_ligne_s1_address;                    // mm_interconnect_0:POS_LIGNE_s1_address -> POS_LIGNE:address
	wire  [31:0] mm_interconnect_0_pos_ligne_s1_readdata;                   // POS_LIGNE:readdata -> mm_interconnect_0:POS_LIGNE_s1_readdata
	wire  [31:0] mm_interconnect_0_memoire_interne_s1_writedata;            // mm_interconnect_0:MEMOIRE_INTERNE_s1_writedata -> MEMOIRE_INTERNE:writedata
	wire   [9:0] mm_interconnect_0_memoire_interne_s1_address;              // mm_interconnect_0:MEMOIRE_INTERNE_s1_address -> MEMOIRE_INTERNE:address
	wire         mm_interconnect_0_memoire_interne_s1_chipselect;           // mm_interconnect_0:MEMOIRE_INTERNE_s1_chipselect -> MEMOIRE_INTERNE:chipselect
	wire         mm_interconnect_0_memoire_interne_s1_clken;                // mm_interconnect_0:MEMOIRE_INTERNE_s1_clken -> MEMOIRE_INTERNE:clken
	wire         mm_interconnect_0_memoire_interne_s1_write;                // mm_interconnect_0:MEMOIRE_INTERNE_s1_write -> MEMOIRE_INTERNE:write
	wire  [31:0] mm_interconnect_0_memoire_interne_s1_readdata;             // MEMOIRE_INTERNE:readdata -> mm_interconnect_0:MEMOIRE_INTERNE_s1_readdata
	wire   [3:0] mm_interconnect_0_memoire_interne_s1_byteenable;           // mm_interconnect_0:MEMOIRE_INTERNE_s1_byteenable -> MEMOIRE_INTERNE:byteenable
	wire         mm_interconnect_0_cpu_jtag_debug_module_waitrequest;       // CPU:jtag_debug_module_waitrequest -> mm_interconnect_0:CPU_jtag_debug_module_waitrequest
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_writedata;         // mm_interconnect_0:CPU_jtag_debug_module_writedata -> CPU:jtag_debug_module_writedata
	wire   [8:0] mm_interconnect_0_cpu_jtag_debug_module_address;           // mm_interconnect_0:CPU_jtag_debug_module_address -> CPU:jtag_debug_module_address
	wire         mm_interconnect_0_cpu_jtag_debug_module_write;             // mm_interconnect_0:CPU_jtag_debug_module_write -> CPU:jtag_debug_module_write
	wire         mm_interconnect_0_cpu_jtag_debug_module_read;              // mm_interconnect_0:CPU_jtag_debug_module_read -> CPU:jtag_debug_module_read
	wire  [31:0] mm_interconnect_0_cpu_jtag_debug_module_readdata;          // CPU:jtag_debug_module_readdata -> mm_interconnect_0:CPU_jtag_debug_module_readdata
	wire         mm_interconnect_0_cpu_jtag_debug_module_debugaccess;       // mm_interconnect_0:CPU_jtag_debug_module_debugaccess -> CPU:jtag_debug_module_debugaccess
	wire   [3:0] mm_interconnect_0_cpu_jtag_debug_module_byteenable;        // mm_interconnect_0:CPU_jtag_debug_module_byteenable -> CPU:jtag_debug_module_byteenable
	wire   [1:0] mm_interconnect_0_vect_cap_s1_address;                     // mm_interconnect_0:VECT_CAP_s1_address -> VECT_CAP:address
	wire  [31:0] mm_interconnect_0_vect_cap_s1_readdata;                    // VECT_CAP:readdata -> mm_interconnect_0:VECT_CAP_s1_readdata
	wire  [31:0] mm_interconnect_0_niveau_s1_writedata;                     // mm_interconnect_0:NIVEAU_s1_writedata -> NIVEAU:writedata
	wire   [1:0] mm_interconnect_0_niveau_s1_address;                       // mm_interconnect_0:NIVEAU_s1_address -> NIVEAU:address
	wire         mm_interconnect_0_niveau_s1_chipselect;                    // mm_interconnect_0:NIVEAU_s1_chipselect -> NIVEAU:chipselect
	wire         mm_interconnect_0_niveau_s1_write;                         // mm_interconnect_0:NIVEAU_s1_write -> NIVEAU:write_n
	wire  [31:0] mm_interconnect_0_niveau_s1_readdata;                      // NIVEAU:readdata -> mm_interconnect_0:NIVEAU_s1_readdata
	wire  [31:0] mm_interconnect_0_cntrl_left_s1_writedata;                 // mm_interconnect_0:CNTRL_LEFT_s1_writedata -> CNTRL_LEFT:writedata
	wire   [1:0] mm_interconnect_0_cntrl_left_s1_address;                   // mm_interconnect_0:CNTRL_LEFT_s1_address -> CNTRL_LEFT:address
	wire         mm_interconnect_0_cntrl_left_s1_chipselect;                // mm_interconnect_0:CNTRL_LEFT_s1_chipselect -> CNTRL_LEFT:chipselect
	wire         mm_interconnect_0_cntrl_left_s1_write;                     // mm_interconnect_0:CNTRL_LEFT_s1_write -> CNTRL_LEFT:write_n
	wire  [31:0] mm_interconnect_0_cntrl_left_s1_readdata;                  // CNTRL_LEFT:readdata -> mm_interconnect_0:CNTRL_LEFT_s1_readdata
	wire   [1:0] mm_interconnect_0_state_crtl_s1_address;                   // mm_interconnect_0:STATE_CRTL_s1_address -> STATE_CRTL:address
	wire  [31:0] mm_interconnect_0_state_crtl_s1_readdata;                  // STATE_CRTL:readdata -> mm_interconnect_0:STATE_CRTL_s1_readdata
	wire   [1:0] mm_interconnect_0_input_s1_address;                        // mm_interconnect_0:INPUT_s1_address -> INPUT:address
	wire  [31:0] mm_interconnect_0_input_s1_readdata;                       // INPUT:readdata -> mm_interconnect_0:INPUT_s1_readdata
	wire   [1:0] mm_interconnect_0_data_ready_r_s1_address;                 // mm_interconnect_0:DATA_READY_R_s1_address -> DATA_READY_R:address
	wire  [31:0] mm_interconnect_0_data_ready_r_s1_readdata;                // DATA_READY_R:readdata -> mm_interconnect_0:DATA_READY_R_s1_readdata
	wire         cpu_instruction_master_waitrequest;                        // mm_interconnect_0:CPU_instruction_master_waitrequest -> CPU:i_waitrequest
	wire  [26:0] cpu_instruction_master_address;                            // CPU:i_address -> mm_interconnect_0:CPU_instruction_master_address
	wire         cpu_instruction_master_read;                               // CPU:i_read -> mm_interconnect_0:CPU_instruction_master_read
	wire  [31:0] cpu_instruction_master_readdata;                           // mm_interconnect_0:CPU_instruction_master_readdata -> CPU:i_readdata
	wire         cpu_data_master_waitrequest;                               // mm_interconnect_0:CPU_data_master_waitrequest -> CPU:d_waitrequest
	wire  [31:0] cpu_data_master_writedata;                                 // CPU:d_writedata -> mm_interconnect_0:CPU_data_master_writedata
	wire  [26:0] cpu_data_master_address;                                   // CPU:d_address -> mm_interconnect_0:CPU_data_master_address
	wire         cpu_data_master_write;                                     // CPU:d_write -> mm_interconnect_0:CPU_data_master_write
	wire         cpu_data_master_read;                                      // CPU:d_read -> mm_interconnect_0:CPU_data_master_read
	wire  [31:0] cpu_data_master_readdata;                                  // mm_interconnect_0:CPU_data_master_readdata -> CPU:d_readdata
	wire         cpu_data_master_debugaccess;                               // CPU:jtag_debug_module_debugaccess_to_roms -> mm_interconnect_0:CPU_data_master_debugaccess
	wire   [3:0] cpu_data_master_byteenable;                                // CPU:d_byteenable -> mm_interconnect_0:CPU_data_master_byteenable
	wire         mm_interconnect_0_sdram_s1_waitrequest;                    // SDRAM:za_waitrequest -> mm_interconnect_0:SDRAM_s1_waitrequest
	wire  [15:0] mm_interconnect_0_sdram_s1_writedata;                      // mm_interconnect_0:SDRAM_s1_writedata -> SDRAM:az_data
	wire  [23:0] mm_interconnect_0_sdram_s1_address;                        // mm_interconnect_0:SDRAM_s1_address -> SDRAM:az_addr
	wire         mm_interconnect_0_sdram_s1_chipselect;                     // mm_interconnect_0:SDRAM_s1_chipselect -> SDRAM:az_cs
	wire         mm_interconnect_0_sdram_s1_write;                          // mm_interconnect_0:SDRAM_s1_write -> SDRAM:az_wr_n
	wire         mm_interconnect_0_sdram_s1_read;                           // mm_interconnect_0:SDRAM_s1_read -> SDRAM:az_rd_n
	wire  [15:0] mm_interconnect_0_sdram_s1_readdata;                       // SDRAM:za_data -> mm_interconnect_0:SDRAM_s1_readdata
	wire         mm_interconnect_0_sdram_s1_readdatavalid;                  // SDRAM:za_valid -> mm_interconnect_0:SDRAM_s1_readdatavalid
	wire   [1:0] mm_interconnect_0_sdram_s1_byteenable;                     // mm_interconnect_0:SDRAM_s1_byteenable -> SDRAM:az_be_n
	wire  [31:0] mm_interconnect_0_output_s1_writedata;                     // mm_interconnect_0:OUTPUT_s1_writedata -> OUTPUT:writedata
	wire   [1:0] mm_interconnect_0_output_s1_address;                       // mm_interconnect_0:OUTPUT_s1_address -> OUTPUT:address
	wire         mm_interconnect_0_output_s1_chipselect;                    // mm_interconnect_0:OUTPUT_s1_chipselect -> OUTPUT:chipselect
	wire         mm_interconnect_0_output_s1_write;                         // mm_interconnect_0:OUTPUT_s1_write -> OUTPUT:write_n
	wire  [31:0] mm_interconnect_0_output_s1_readdata;                      // OUTPUT:readdata -> mm_interconnect_0:OUTPUT_s1_readdata
	wire  [31:0] mm_interconnect_0_cntrl_right_s1_writedata;                // mm_interconnect_0:CNTRL_RIGHT_s1_writedata -> CNTRL_RIGHT:writedata
	wire   [1:0] mm_interconnect_0_cntrl_right_s1_address;                  // mm_interconnect_0:CNTRL_RIGHT_s1_address -> CNTRL_RIGHT:address
	wire         mm_interconnect_0_cntrl_right_s1_chipselect;               // mm_interconnect_0:CNTRL_RIGHT_s1_chipselect -> CNTRL_RIGHT:chipselect
	wire         mm_interconnect_0_cntrl_right_s1_write;                    // mm_interconnect_0:CNTRL_RIGHT_s1_write -> CNTRL_RIGHT:write_n
	wire  [31:0] mm_interconnect_0_cntrl_right_s1_readdata;                 // CNTRL_RIGHT:readdata -> mm_interconnect_0:CNTRL_RIGHT_s1_readdata
	wire  [31:0] mm_interconnect_0_start_sl_s1_writedata;                   // mm_interconnect_0:START_SL_s1_writedata -> START_SL:writedata
	wire   [1:0] mm_interconnect_0_start_sl_s1_address;                     // mm_interconnect_0:START_SL_s1_address -> START_SL:address
	wire         mm_interconnect_0_start_sl_s1_chipselect;                  // mm_interconnect_0:START_SL_s1_chipselect -> START_SL:chipselect
	wire         mm_interconnect_0_start_sl_s1_write;                       // mm_interconnect_0:START_SL_s1_write -> START_SL:write_n
	wire  [31:0] mm_interconnect_0_start_sl_s1_readdata;                    // START_SL:readdata -> mm_interconnect_0:START_SL_s1_readdata
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest; // JTAG_UART:av_waitrequest -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_waitrequest
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata;   // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_writedata -> JTAG_UART:av_writedata
	wire   [0:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_address;     // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_address -> JTAG_UART:av_address
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect;  // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_chipselect -> JTAG_UART:av_chipselect
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_write;       // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_write -> JTAG_UART:av_write_n
	wire         mm_interconnect_0_jtag_uart_avalon_jtag_slave_read;        // mm_interconnect_0:JTAG_UART_avalon_jtag_slave_read -> JTAG_UART:av_read_n
	wire  [31:0] mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata;    // JTAG_UART:av_readdata -> mm_interconnect_0:JTAG_UART_avalon_jtag_slave_readdata
	wire   [1:0] mm_interconnect_0_data_0r_s1_address;                      // mm_interconnect_0:DATA_0R_s1_address -> DATA_0R:address
	wire  [31:0] mm_interconnect_0_data_0r_s1_readdata;                     // DATA_0R:readdata -> mm_interconnect_0:DATA_0R_s1_readdata
	wire  [31:0] cpu_d_irq_irq;                                             // irq_mapper:sender_irq -> CPU:d_irq
	wire         irq_mapper_receiver0_irq;                                  // irq_synchronizer:sender_irq -> irq_mapper:receiver0_irq
	wire   [0:0] irq_synchronizer_receiver_irq;                             // JTAG_UART:av_irq -> irq_synchronizer:receiver_irq
	wire         rst_controller_reset_out_reset;                            // rst_controller:reset_out -> [CNTRL_LEFT:reset_n, CNTRL_RIGHT:reset_n, CPU:reset_n, DATA_0R:reset_n, DATA_READY_R:reset_n, INPUT:reset_n, MEMOIRE_INTERNE:reset, NIVEAU:reset_n, POS_LIGNE:reset_n, SDRAM:reset_n, START_SL:reset_n, STATE_CRTL:reset_n, VECT_CAP:reset_n, irq_mapper:reset, irq_synchronizer:sender_reset, mm_interconnect_0:CPU_reset_n_reset_bridge_in_reset_reset, rst_translator:in_reset]
	wire         rst_controller_reset_out_reset_req;                        // rst_controller:reset_req -> [CPU:reset_req, MEMOIRE_INTERNE:reset_req, rst_translator:reset_req_in]
	wire         cpu_jtag_debug_module_reset_reset;                         // CPU:jtag_debug_module_resetrequest -> [rst_controller:reset_in1, rst_controller_001:reset_in1]
	wire         rst_controller_001_reset_out_reset;                        // rst_controller_001:reset_out -> [JTAG_UART:rst_n, OUTPUT:reset_n, clocks:reset, irq_synchronizer:receiver_reset, mm_interconnect_0:OUTPUT_reset_reset_bridge_in_reset_reset]

	nios_system_CPU cpu (
		.clk                                   (clocks_sys_clk_clk),                                  //                       clk.clk
		.reset_n                               (~rst_controller_reset_out_reset),                     //                   reset_n.reset_n
		.reset_req                             (rst_controller_reset_out_reset_req),                  //                          .reset_req
		.d_address                             (cpu_data_master_address),                             //               data_master.address
		.d_byteenable                          (cpu_data_master_byteenable),                          //                          .byteenable
		.d_read                                (cpu_data_master_read),                                //                          .read
		.d_readdata                            (cpu_data_master_readdata),                            //                          .readdata
		.d_waitrequest                         (cpu_data_master_waitrequest),                         //                          .waitrequest
		.d_write                               (cpu_data_master_write),                               //                          .write
		.d_writedata                           (cpu_data_master_writedata),                           //                          .writedata
		.jtag_debug_module_debugaccess_to_roms (cpu_data_master_debugaccess),                         //                          .debugaccess
		.i_address                             (cpu_instruction_master_address),                      //        instruction_master.address
		.i_read                                (cpu_instruction_master_read),                         //                          .read
		.i_readdata                            (cpu_instruction_master_readdata),                     //                          .readdata
		.i_waitrequest                         (cpu_instruction_master_waitrequest),                  //                          .waitrequest
		.d_irq                                 (cpu_d_irq_irq),                                       //                     d_irq.irq
		.jtag_debug_module_resetrequest        (cpu_jtag_debug_module_reset_reset),                   //   jtag_debug_module_reset.reset
		.jtag_debug_module_address             (mm_interconnect_0_cpu_jtag_debug_module_address),     //         jtag_debug_module.address
		.jtag_debug_module_byteenable          (mm_interconnect_0_cpu_jtag_debug_module_byteenable),  //                          .byteenable
		.jtag_debug_module_debugaccess         (mm_interconnect_0_cpu_jtag_debug_module_debugaccess), //                          .debugaccess
		.jtag_debug_module_read                (mm_interconnect_0_cpu_jtag_debug_module_read),        //                          .read
		.jtag_debug_module_readdata            (mm_interconnect_0_cpu_jtag_debug_module_readdata),    //                          .readdata
		.jtag_debug_module_waitrequest         (mm_interconnect_0_cpu_jtag_debug_module_waitrequest), //                          .waitrequest
		.jtag_debug_module_write               (mm_interconnect_0_cpu_jtag_debug_module_write),       //                          .write
		.jtag_debug_module_writedata           (mm_interconnect_0_cpu_jtag_debug_module_writedata),   //                          .writedata
		.no_ci_readra                          ()                                                     // custom_instruction_master.readra
	);

	nios_system_MEMOIRE_INTERNE memoire_interne (
		.clk        (clocks_sys_clk_clk),                              //   clk1.clk
		.address    (mm_interconnect_0_memoire_interne_s1_address),    //     s1.address
		.clken      (mm_interconnect_0_memoire_interne_s1_clken),      //       .clken
		.chipselect (mm_interconnect_0_memoire_interne_s1_chipselect), //       .chipselect
		.write      (mm_interconnect_0_memoire_interne_s1_write),      //       .write
		.readdata   (mm_interconnect_0_memoire_interne_s1_readdata),   //       .readdata
		.writedata  (mm_interconnect_0_memoire_interne_s1_writedata),  //       .writedata
		.byteenable (mm_interconnect_0_memoire_interne_s1_byteenable), //       .byteenable
		.reset      (rst_controller_reset_out_reset),                  // reset1.reset
		.reset_req  (rst_controller_reset_out_reset_req)               //       .reset_req
	);

	nios_system_INPUT input_inst (
		.clk      (clocks_sys_clk_clk),                  //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),     //               reset.reset_n
		.address  (mm_interconnect_0_input_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_input_s1_readdata), //                    .readdata
		.in_port  (switches_export)                      // external_connection.export
	);

	nios_system_OUTPUT output_inst (
		.clk        (clk_clk),                                //                 clk.clk
		.reset_n    (~rst_controller_001_reset_out_reset),    //               reset.reset_n
		.address    (mm_interconnect_0_output_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_output_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_output_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_output_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_output_s1_readdata),   //                    .readdata
		.out_port   (leds_export)                             // external_connection.export
	);

	nios_system_JTAG_UART jtag_uart (
		.clk            (clk_clk),                                                   //               clk.clk
		.rst_n          (~rst_controller_001_reset_out_reset),                       //             reset.reset_n
		.av_chipselect  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  // avalon_jtag_slave.chipselect
		.av_address     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //                  .address
		.av_read_n      (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),       //                  .read_n
		.av_readdata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                  .readdata
		.av_write_n     (~mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),      //                  .write_n
		.av_writedata   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                  .writedata
		.av_waitrequest (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                  .waitrequest
		.av_irq         (irq_synchronizer_receiver_irq)                              //               irq.irq
	);

	nios_system_SDRAM sdram (
		.clk            (clocks_sys_clk_clk),                       //   clk.clk
		.reset_n        (~rst_controller_reset_out_reset),          // reset.reset_n
		.az_addr        (mm_interconnect_0_sdram_s1_address),       //    s1.address
		.az_be_n        (~mm_interconnect_0_sdram_s1_byteenable),   //      .byteenable_n
		.az_cs          (mm_interconnect_0_sdram_s1_chipselect),    //      .chipselect
		.az_data        (mm_interconnect_0_sdram_s1_writedata),     //      .writedata
		.az_rd_n        (~mm_interconnect_0_sdram_s1_read),         //      .read_n
		.az_wr_n        (~mm_interconnect_0_sdram_s1_write),        //      .write_n
		.za_data        (mm_interconnect_0_sdram_s1_readdata),      //      .readdata
		.za_valid       (mm_interconnect_0_sdram_s1_readdatavalid), //      .readdatavalid
		.za_waitrequest (mm_interconnect_0_sdram_s1_waitrequest),   //      .waitrequest
		.zs_addr        (sdram_wire_addr),                          //  wire.export
		.zs_ba          (sdram_wire_ba),                            //      .export
		.zs_cas_n       (sdram_wire_cas_n),                         //      .export
		.zs_cke         (sdram_wire_cke),                           //      .export
		.zs_cs_n        (sdram_wire_cs_n),                          //      .export
		.zs_dq          (sdram_wire_dq),                            //      .export
		.zs_dqm         (sdram_wire_dqm),                           //      .export
		.zs_ras_n       (sdram_wire_ras_n),                         //      .export
		.zs_we_n        (sdram_wire_we_n)                           //      .export
	);

	nios_system_CNTRL_LEFT cntrl_left (
		.clk        (clocks_sys_clk_clk),                         //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),            //               reset.reset_n
		.address    (mm_interconnect_0_cntrl_left_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_cntrl_left_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_cntrl_left_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_cntrl_left_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_cntrl_left_s1_readdata),   //                    .readdata
		.out_port   (cntrl_left_export)                           // external_connection.export
	);

	nios_system_CNTRL_LEFT cntrl_right (
		.clk        (clocks_sys_clk_clk),                          //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),             //               reset.reset_n
		.address    (mm_interconnect_0_cntrl_right_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_cntrl_right_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_cntrl_right_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_cntrl_right_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_cntrl_right_s1_readdata),   //                    .readdata
		.out_port   (cntrl_right_export)                           // external_connection.export
	);

	nios_system_INPUT data_0r (
		.clk      (clocks_sys_clk_clk),                    //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),       //               reset.reset_n
		.address  (mm_interconnect_0_data_0r_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_data_0r_s1_readdata), //                    .readdata
		.in_port  (data_0r_external_connection_export)     // external_connection.export
	);

	nios_system_DATA_READY_R data_ready_r (
		.clk      (clocks_sys_clk_clk),                         //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),            //               reset.reset_n
		.address  (mm_interconnect_0_data_ready_r_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_data_ready_r_s1_readdata), //                    .readdata
		.in_port  (data_ready_r_external_connection_export)     // external_connection.export
	);

	nios_system_VECT_CAP vect_cap (
		.clk      (clocks_sys_clk_clk),                     //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address  (mm_interconnect_0_vect_cap_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_vect_cap_s1_readdata), //                    .readdata
		.in_port  (vect_cap_external_connection_export)     // external_connection.export
	);

	nios_system_OUTPUT niveau (
		.clk        (clocks_sys_clk_clk),                     //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),        //               reset.reset_n
		.address    (mm_interconnect_0_niveau_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_niveau_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_niveau_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_niveau_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_niveau_s1_readdata),   //                    .readdata
		.out_port   (niveau_external_connection_export)       // external_connection.export
	);

	nios_system_START_SL start_sl (
		.clk        (clocks_sys_clk_clk),                       //                 clk.clk
		.reset_n    (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address    (mm_interconnect_0_start_sl_s1_address),    //                  s1.address
		.write_n    (~mm_interconnect_0_start_sl_s1_write),     //                    .write_n
		.writedata  (mm_interconnect_0_start_sl_s1_writedata),  //                    .writedata
		.chipselect (mm_interconnect_0_start_sl_s1_chipselect), //                    .chipselect
		.readdata   (mm_interconnect_0_start_sl_s1_readdata),   //                    .readdata
		.out_port   (start_sl_external_connection_export)       // external_connection.export
	);

	nios_system_POS_LIGNE pos_ligne (
		.clk      (clocks_sys_clk_clk),                      //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),         //               reset.reset_n
		.address  (mm_interconnect_0_pos_ligne_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_pos_ligne_s1_readdata), //                    .readdata
		.in_port  (pos_ligne_external_connection_export)     // external_connection.export
	);

	nios_system_STATE_CRTL state_crtl (
		.clk      (clocks_sys_clk_clk),                       //                 clk.clk
		.reset_n  (~rst_controller_reset_out_reset),          //               reset.reset_n
		.address  (mm_interconnect_0_state_crtl_s1_address),  //                  s1.address
		.readdata (mm_interconnect_0_state_crtl_s1_readdata), //                    .readdata
		.in_port  (state_crtl_external_connection_export)     // external_connection.export
	);

	nios_system_clocks clocks (
		.CLOCK_50    (clk_clk),                            //       clk_in_primary.clk
		.reset       (rst_controller_001_reset_out_reset), // clk_in_primary_reset.reset
		.sys_clk     (clocks_sys_clk_clk),                 //              sys_clk.clk
		.sys_reset_n (),                                   //        sys_clk_reset.reset_n
		.SDRAM_CLK   (sdram_clk_clk)                       //            sdram_clk.clk
	);

	nios_system_mm_interconnect_0 mm_interconnect_0 (
		.clk_0_clk_clk                            (clk_clk),                                                   //                          clk_0_clk.clk
		.clocks_sys_clk_clk                       (clocks_sys_clk_clk),                                        //                     clocks_sys_clk.clk
		.CPU_reset_n_reset_bridge_in_reset_reset  (rst_controller_reset_out_reset),                            //  CPU_reset_n_reset_bridge_in_reset.reset
		.OUTPUT_reset_reset_bridge_in_reset_reset (rst_controller_001_reset_out_reset),                        // OUTPUT_reset_reset_bridge_in_reset.reset
		.CPU_data_master_address                  (cpu_data_master_address),                                   //                    CPU_data_master.address
		.CPU_data_master_waitrequest              (cpu_data_master_waitrequest),                               //                                   .waitrequest
		.CPU_data_master_byteenable               (cpu_data_master_byteenable),                                //                                   .byteenable
		.CPU_data_master_read                     (cpu_data_master_read),                                      //                                   .read
		.CPU_data_master_readdata                 (cpu_data_master_readdata),                                  //                                   .readdata
		.CPU_data_master_write                    (cpu_data_master_write),                                     //                                   .write
		.CPU_data_master_writedata                (cpu_data_master_writedata),                                 //                                   .writedata
		.CPU_data_master_debugaccess              (cpu_data_master_debugaccess),                               //                                   .debugaccess
		.CPU_instruction_master_address           (cpu_instruction_master_address),                            //             CPU_instruction_master.address
		.CPU_instruction_master_waitrequest       (cpu_instruction_master_waitrequest),                        //                                   .waitrequest
		.CPU_instruction_master_read              (cpu_instruction_master_read),                               //                                   .read
		.CPU_instruction_master_readdata          (cpu_instruction_master_readdata),                           //                                   .readdata
		.CNTRL_LEFT_s1_address                    (mm_interconnect_0_cntrl_left_s1_address),                   //                      CNTRL_LEFT_s1.address
		.CNTRL_LEFT_s1_write                      (mm_interconnect_0_cntrl_left_s1_write),                     //                                   .write
		.CNTRL_LEFT_s1_readdata                   (mm_interconnect_0_cntrl_left_s1_readdata),                  //                                   .readdata
		.CNTRL_LEFT_s1_writedata                  (mm_interconnect_0_cntrl_left_s1_writedata),                 //                                   .writedata
		.CNTRL_LEFT_s1_chipselect                 (mm_interconnect_0_cntrl_left_s1_chipselect),                //                                   .chipselect
		.CNTRL_RIGHT_s1_address                   (mm_interconnect_0_cntrl_right_s1_address),                  //                     CNTRL_RIGHT_s1.address
		.CNTRL_RIGHT_s1_write                     (mm_interconnect_0_cntrl_right_s1_write),                    //                                   .write
		.CNTRL_RIGHT_s1_readdata                  (mm_interconnect_0_cntrl_right_s1_readdata),                 //                                   .readdata
		.CNTRL_RIGHT_s1_writedata                 (mm_interconnect_0_cntrl_right_s1_writedata),                //                                   .writedata
		.CNTRL_RIGHT_s1_chipselect                (mm_interconnect_0_cntrl_right_s1_chipselect),               //                                   .chipselect
		.CPU_jtag_debug_module_address            (mm_interconnect_0_cpu_jtag_debug_module_address),           //              CPU_jtag_debug_module.address
		.CPU_jtag_debug_module_write              (mm_interconnect_0_cpu_jtag_debug_module_write),             //                                   .write
		.CPU_jtag_debug_module_read               (mm_interconnect_0_cpu_jtag_debug_module_read),              //                                   .read
		.CPU_jtag_debug_module_readdata           (mm_interconnect_0_cpu_jtag_debug_module_readdata),          //                                   .readdata
		.CPU_jtag_debug_module_writedata          (mm_interconnect_0_cpu_jtag_debug_module_writedata),         //                                   .writedata
		.CPU_jtag_debug_module_byteenable         (mm_interconnect_0_cpu_jtag_debug_module_byteenable),        //                                   .byteenable
		.CPU_jtag_debug_module_waitrequest        (mm_interconnect_0_cpu_jtag_debug_module_waitrequest),       //                                   .waitrequest
		.CPU_jtag_debug_module_debugaccess        (mm_interconnect_0_cpu_jtag_debug_module_debugaccess),       //                                   .debugaccess
		.DATA_0R_s1_address                       (mm_interconnect_0_data_0r_s1_address),                      //                         DATA_0R_s1.address
		.DATA_0R_s1_readdata                      (mm_interconnect_0_data_0r_s1_readdata),                     //                                   .readdata
		.DATA_READY_R_s1_address                  (mm_interconnect_0_data_ready_r_s1_address),                 //                    DATA_READY_R_s1.address
		.DATA_READY_R_s1_readdata                 (mm_interconnect_0_data_ready_r_s1_readdata),                //                                   .readdata
		.INPUT_s1_address                         (mm_interconnect_0_input_s1_address),                        //                           INPUT_s1.address
		.INPUT_s1_readdata                        (mm_interconnect_0_input_s1_readdata),                       //                                   .readdata
		.JTAG_UART_avalon_jtag_slave_address      (mm_interconnect_0_jtag_uart_avalon_jtag_slave_address),     //        JTAG_UART_avalon_jtag_slave.address
		.JTAG_UART_avalon_jtag_slave_write        (mm_interconnect_0_jtag_uart_avalon_jtag_slave_write),       //                                   .write
		.JTAG_UART_avalon_jtag_slave_read         (mm_interconnect_0_jtag_uart_avalon_jtag_slave_read),        //                                   .read
		.JTAG_UART_avalon_jtag_slave_readdata     (mm_interconnect_0_jtag_uart_avalon_jtag_slave_readdata),    //                                   .readdata
		.JTAG_UART_avalon_jtag_slave_writedata    (mm_interconnect_0_jtag_uart_avalon_jtag_slave_writedata),   //                                   .writedata
		.JTAG_UART_avalon_jtag_slave_waitrequest  (mm_interconnect_0_jtag_uart_avalon_jtag_slave_waitrequest), //                                   .waitrequest
		.JTAG_UART_avalon_jtag_slave_chipselect   (mm_interconnect_0_jtag_uart_avalon_jtag_slave_chipselect),  //                                   .chipselect
		.MEMOIRE_INTERNE_s1_address               (mm_interconnect_0_memoire_interne_s1_address),              //                 MEMOIRE_INTERNE_s1.address
		.MEMOIRE_INTERNE_s1_write                 (mm_interconnect_0_memoire_interne_s1_write),                //                                   .write
		.MEMOIRE_INTERNE_s1_readdata              (mm_interconnect_0_memoire_interne_s1_readdata),             //                                   .readdata
		.MEMOIRE_INTERNE_s1_writedata             (mm_interconnect_0_memoire_interne_s1_writedata),            //                                   .writedata
		.MEMOIRE_INTERNE_s1_byteenable            (mm_interconnect_0_memoire_interne_s1_byteenable),           //                                   .byteenable
		.MEMOIRE_INTERNE_s1_chipselect            (mm_interconnect_0_memoire_interne_s1_chipselect),           //                                   .chipselect
		.MEMOIRE_INTERNE_s1_clken                 (mm_interconnect_0_memoire_interne_s1_clken),                //                                   .clken
		.NIVEAU_s1_address                        (mm_interconnect_0_niveau_s1_address),                       //                          NIVEAU_s1.address
		.NIVEAU_s1_write                          (mm_interconnect_0_niveau_s1_write),                         //                                   .write
		.NIVEAU_s1_readdata                       (mm_interconnect_0_niveau_s1_readdata),                      //                                   .readdata
		.NIVEAU_s1_writedata                      (mm_interconnect_0_niveau_s1_writedata),                     //                                   .writedata
		.NIVEAU_s1_chipselect                     (mm_interconnect_0_niveau_s1_chipselect),                    //                                   .chipselect
		.OUTPUT_s1_address                        (mm_interconnect_0_output_s1_address),                       //                          OUTPUT_s1.address
		.OUTPUT_s1_write                          (mm_interconnect_0_output_s1_write),                         //                                   .write
		.OUTPUT_s1_readdata                       (mm_interconnect_0_output_s1_readdata),                      //                                   .readdata
		.OUTPUT_s1_writedata                      (mm_interconnect_0_output_s1_writedata),                     //                                   .writedata
		.OUTPUT_s1_chipselect                     (mm_interconnect_0_output_s1_chipselect),                    //                                   .chipselect
		.POS_LIGNE_s1_address                     (mm_interconnect_0_pos_ligne_s1_address),                    //                       POS_LIGNE_s1.address
		.POS_LIGNE_s1_readdata                    (mm_interconnect_0_pos_ligne_s1_readdata),                   //                                   .readdata
		.SDRAM_s1_address                         (mm_interconnect_0_sdram_s1_address),                        //                           SDRAM_s1.address
		.SDRAM_s1_write                           (mm_interconnect_0_sdram_s1_write),                          //                                   .write
		.SDRAM_s1_read                            (mm_interconnect_0_sdram_s1_read),                           //                                   .read
		.SDRAM_s1_readdata                        (mm_interconnect_0_sdram_s1_readdata),                       //                                   .readdata
		.SDRAM_s1_writedata                       (mm_interconnect_0_sdram_s1_writedata),                      //                                   .writedata
		.SDRAM_s1_byteenable                      (mm_interconnect_0_sdram_s1_byteenable),                     //                                   .byteenable
		.SDRAM_s1_readdatavalid                   (mm_interconnect_0_sdram_s1_readdatavalid),                  //                                   .readdatavalid
		.SDRAM_s1_waitrequest                     (mm_interconnect_0_sdram_s1_waitrequest),                    //                                   .waitrequest
		.SDRAM_s1_chipselect                      (mm_interconnect_0_sdram_s1_chipselect),                     //                                   .chipselect
		.START_SL_s1_address                      (mm_interconnect_0_start_sl_s1_address),                     //                        START_SL_s1.address
		.START_SL_s1_write                        (mm_interconnect_0_start_sl_s1_write),                       //                                   .write
		.START_SL_s1_readdata                     (mm_interconnect_0_start_sl_s1_readdata),                    //                                   .readdata
		.START_SL_s1_writedata                    (mm_interconnect_0_start_sl_s1_writedata),                   //                                   .writedata
		.START_SL_s1_chipselect                   (mm_interconnect_0_start_sl_s1_chipselect),                  //                                   .chipselect
		.STATE_CRTL_s1_address                    (mm_interconnect_0_state_crtl_s1_address),                   //                      STATE_CRTL_s1.address
		.STATE_CRTL_s1_readdata                   (mm_interconnect_0_state_crtl_s1_readdata),                  //                                   .readdata
		.VECT_CAP_s1_address                      (mm_interconnect_0_vect_cap_s1_address),                     //                        VECT_CAP_s1.address
		.VECT_CAP_s1_readdata                     (mm_interconnect_0_vect_cap_s1_readdata)                     //                                   .readdata
	);

	nios_system_irq_mapper irq_mapper (
		.clk           (clocks_sys_clk_clk),             //       clk.clk
		.reset         (rst_controller_reset_out_reset), // clk_reset.reset
		.receiver0_irq (irq_mapper_receiver0_irq),       // receiver0.irq
		.sender_irq    (cpu_d_irq_irq)                   //    sender.irq
	);

	altera_irq_clock_crosser #(
		.IRQ_WIDTH (1)
	) irq_synchronizer (
		.receiver_clk   (clk_clk),                            //       receiver_clk.clk
		.sender_clk     (clocks_sys_clk_clk),                 //         sender_clk.clk
		.receiver_reset (rst_controller_001_reset_out_reset), // receiver_clk_reset.reset
		.sender_reset   (rst_controller_reset_out_reset),     //   sender_clk_reset.reset
		.receiver_irq   (irq_synchronizer_receiver_irq),      //           receiver.irq
		.sender_irq     (irq_mapper_receiver0_irq)            //             sender.irq
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (1),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (clocks_sys_clk_clk),                 //       clk.clk
		.reset_out      (rst_controller_reset_out_reset),     // reset_out.reset
		.reset_req      (rst_controller_reset_out_reset_req), //          .reset_req
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

	altera_reset_controller #(
		.NUM_RESET_INPUTS          (2),
		.OUTPUT_RESET_SYNC_EDGES   ("deassert"),
		.SYNC_DEPTH                (2),
		.RESET_REQUEST_PRESENT     (0),
		.RESET_REQ_WAIT_TIME       (1),
		.MIN_RST_ASSERTION_TIME    (3),
		.RESET_REQ_EARLY_DSRT_TIME (1),
		.USE_RESET_REQUEST_IN0     (0),
		.USE_RESET_REQUEST_IN1     (0),
		.USE_RESET_REQUEST_IN2     (0),
		.USE_RESET_REQUEST_IN3     (0),
		.USE_RESET_REQUEST_IN4     (0),
		.USE_RESET_REQUEST_IN5     (0),
		.USE_RESET_REQUEST_IN6     (0),
		.USE_RESET_REQUEST_IN7     (0),
		.USE_RESET_REQUEST_IN8     (0),
		.USE_RESET_REQUEST_IN9     (0),
		.USE_RESET_REQUEST_IN10    (0),
		.USE_RESET_REQUEST_IN11    (0),
		.USE_RESET_REQUEST_IN12    (0),
		.USE_RESET_REQUEST_IN13    (0),
		.USE_RESET_REQUEST_IN14    (0),
		.USE_RESET_REQUEST_IN15    (0),
		.ADAPT_RESET_REQUEST       (0)
	) rst_controller_001 (
		.reset_in0      (~reset_reset_n),                     // reset_in0.reset
		.reset_in1      (cpu_jtag_debug_module_reset_reset),  // reset_in1.reset
		.clk            (clk_clk),                            //       clk.clk
		.reset_out      (rst_controller_001_reset_out_reset), // reset_out.reset
		.reset_req      (),                                   // (terminated)
		.reset_req_in0  (1'b0),                               // (terminated)
		.reset_req_in1  (1'b0),                               // (terminated)
		.reset_in2      (1'b0),                               // (terminated)
		.reset_req_in2  (1'b0),                               // (terminated)
		.reset_in3      (1'b0),                               // (terminated)
		.reset_req_in3  (1'b0),                               // (terminated)
		.reset_in4      (1'b0),                               // (terminated)
		.reset_req_in4  (1'b0),                               // (terminated)
		.reset_in5      (1'b0),                               // (terminated)
		.reset_req_in5  (1'b0),                               // (terminated)
		.reset_in6      (1'b0),                               // (terminated)
		.reset_req_in6  (1'b0),                               // (terminated)
		.reset_in7      (1'b0),                               // (terminated)
		.reset_req_in7  (1'b0),                               // (terminated)
		.reset_in8      (1'b0),                               // (terminated)
		.reset_req_in8  (1'b0),                               // (terminated)
		.reset_in9      (1'b0),                               // (terminated)
		.reset_req_in9  (1'b0),                               // (terminated)
		.reset_in10     (1'b0),                               // (terminated)
		.reset_req_in10 (1'b0),                               // (terminated)
		.reset_in11     (1'b0),                               // (terminated)
		.reset_req_in11 (1'b0),                               // (terminated)
		.reset_in12     (1'b0),                               // (terminated)
		.reset_req_in12 (1'b0),                               // (terminated)
		.reset_in13     (1'b0),                               // (terminated)
		.reset_req_in13 (1'b0),                               // (terminated)
		.reset_in14     (1'b0),                               // (terminated)
		.reset_req_in14 (1'b0),                               // (terminated)
		.reset_in15     (1'b0),                               // (terminated)
		.reset_req_in15 (1'b0)                                // (terminated)
	);

endmodule
